{
	"lib":	"E:/Developments/Cadaqs/caNamespace/castudio/xcross/xlang/xlang/xlibrarys/FileSystem/x64/debug/FileSystem.lix",
	"md":	"E:/Developments/Cadaqs/caNamespace/castudio/xcross/xlang/xlang/xlibrarys/FileSystem/readme.md",
	"icon":	"",
	"comment":	"",
	"archs":	{
},
	"package":	"FileSystem",
	"version":	"1.0.0.3",
	"descr":	"用于文件常规文件处理  遍历等操作",
	"author":	"https://github.com/ixlang/xlibraries"
}