{
	"lib":	"E:/Developments/Cadaqs/caNamespace/castudio/xcross/xlang/xlang/xlibrarys/QT&XLIB/QXLibrary/debug/QXLibrary.lix",
	"md":	"E:/Developments/Cadaqs/caNamespace/castudio/xcross/xlang/xlang/xlibrarys/QT&XLIB/readme.md",
	"icon":	"E:/Developments/Cadaqs/caNamespace/castudio/xcross/xlang/xide/config/qt.png",
	"comment":	"",
	"archs":	{
		"0":	{
			"0":	[],
			"1":	[],
			"2":	[],
			"3":	[]
		},
		"1":	{
			"0":	["E:/Developments/Cadaqs/caNamespace/castudio/xcross/xlang/xlang/xlibrarys/QXLibrary/Win32/Release/QXLibrary.dll"],
			"1":	["E:/Developments/Cadaqs/caNamespace/castudio/xcross/Binary/Linux/i686/libQXLibrary.so"],
			"2":	[],
			"3":	[]
		},
		"2":	{
			"0":	["E:/Developments/Cadaqs/caNamespace/castudio/xcross/xlang/xlang/xlibrarys/QXLibrary/x64/Release/QXLibrary.dll"],
			"1":	["E:/Developments/Cadaqs/caNamespace/castudio/xcross/Binary/Linux/x86_64/libQXLibrary.so"],
			"2":	["E:/Developments/Cadaqs/caNamespace/castudio/xcross/Binary/Darwin/i386/libQXLibrary.dylib"],
			"3":	[]
		},
		"3":	{
			"0":	[],
			"1":	[],
			"2":	[],
			"3":	[]
		},
		"4":	{
			"0":	[],
			"1":	[],
			"2":	[],
			"3":	[]
		}
	},
	"package":	"Qt5.9.1",
	"version":	"5.9.1.15",
	"descr":	"优秀的跨平台界面库",
	"author":	"https://github.com/ixlang/xlibraries"
}