#pragma once
#include <QtCore/qglobal.h>
#include <QtWidgets/QtWidgets>
#include <QPrintDialog>
#include <QPrinter>
#include <QPrintPreviewDialog>
#include <QObjectCleanupHandler>
#ifndef MOBILE_APP
#include <LimeReport> 
#endif
//高版本下要加
//Qt5WindowsUIAutomationSupport.lib
#define XHANDLE "xhandle"
#ifndef MOBILE_APP
#include <QtitanDocking/include/QtitanDocking.h>
#endif
extern int xhangle_reg_id;

#define MAKEPROPERTY(a) QVariant::fromValue(XMetaHandle(a))
#define GETPROPERTY_VALUE value<XMetaHandle>()
#define XMetaPtr XMetaHandle
#define CHECK_NONE_HANDLE(h) if((h) == 0){XThread thread; gs_env->throwNativeException(thread.getThread(), "native handle is 0"); }


#include <QMediaPlayer>
#include <QAudioOutput>
#include <QVideoWidget>
#include <QAudioInput>
#include <QMediaService>
#include <QAudioDeviceInfo>

#if !defined(QT_NO_OPENGL)
#include <QOpenGLFunctions_1_0>
#include <QOpenGLFunctions_1_1>
#ifdef MOBILE_APP
#include <QOpenGLFunctions_ES2.h>
#endif
#include <QGLShaderProgram>
#endif

#include <QtUiTools/QUiLoader>
#ifdef WIN32
#include <Qt4Qt5/Qsci/qsciscintilla.h>
#include <Qt4Qt5/Qsci/qscicommandset.h>
#include <Qt4Qt5/Qsci/qsciprinter.h>
#include "../../../../../../xcross/xcross/xnl.h"
#include "../../../../../thirds/qtPropertyBrowser/QtPropertyBrowser-master/src/qtvariantproperty.h"
#include "../../../../../thirds/qtPropertyBrowser/QtPropertyBrowser-master/src/qtpropertymanager.h"
#include "../../../../../thirds/qtPropertyBrowser/QtPropertyBrowser-master/src/qteditorfactory.h"
#include "../../../../../thirds/qtPropertyBrowser/QtPropertyBrowser-master/src/qttreepropertybrowser.h"
#elif defined(__linux__)
#include <Qt4Qt5/Qsci/qsciscintilla.h>
#include <Qt4Qt5/Qsci/qscicommandset.h>
#include <Qt4Qt5/Qsci/qsciprinter.h>
#include "../../../../../../xcross/xcross/xnl.h"
#include "../../../../../thirds/qtPropertyBrowser/QtPropertyBrowser-master/src/qtvariantproperty.h"
#include "../../../../../thirds/qtPropertyBrowser/QtPropertyBrowser-master/src/qtpropertymanager.h"
#include "../../../../../thirds/qtPropertyBrowser/QtPropertyBrowser-master/src/qteditorfactory.h"
#include "../../../../../thirds/qtPropertyBrowser/QtPropertyBrowser-master/src/qttreepropertybrowser.h"
#elif defined(__APPLE__)
#include <QtUiTools/QUiLoader>
#include "../../../../../xcross/xnl.h"
#include <Qt4Qt5/Qsci/qsciscintilla.h>
#include <Qt4Qt5/Qsci/qscicommandset.h>
#include <Qt4Qt5/Qsci/qsciprinter.h>
#include "../../../../../thirds/qtPropertyBrowser/QtPropertyBrowser-master/src/qtvariantproperty.h"
#include "../../../../../thirds/qtPropertyBrowser/QtPropertyBrowser-master/src/qtpropertymanager.h"
#include "../../../../../thirds/qtPropertyBrowser/QtPropertyBrowser-master/src/qteditorfactory.h"
#include "../../../../../thirds/qtPropertyBrowser/QtPropertyBrowser-master/src/qttreepropertybrowser.h"
#endif

/*#define _CRTDBG_MAP_ALLOC
#include <stdlib.h>
#include <crtdbg.h>

#ifdef _DEBUG  
#define new new(_NORMAL_BLOCK, __FILE__, __LINE__)  
#endif  */

extern XNLEnv * gs_env ;
extern XContext * ui_thread;
extern bool ui_release;
extern Qt::HANDLE ui_thread_id;

class XThread {
	XContext * thread;
	bool release;
public:

	XThread() {
		release = 0;
		if (QThread::currentThreadId() == ui_thread_id) {
			thread = ui_thread;
			//gs_env->throwNativeException(ui_thread, "Current thread is not the UI thread");
		}else {
			thread = gs_env->getContext(&release);
		}
	}

	~XThread() {
		if (release) {
			gs_env->releaseContext(thread);
		}
	}

	XContext * getThread() {
		return thread;
	}
};

#include <QtWidgets/QApplication>
#include "qtype.h"

#ifndef BUILD_STATIC
# if defined(QXLIBRARY_LIB)
#  define QXLIBRARY_EXPORT Q_DECL_EXPORT
# else
#  define QXLIBRARY_EXPORT Q_DECL_IMPORT
# endif
#else
# define QXLIBRARY_EXPORT
#endif



#ifndef WIN32
template<class T>
size_t _countof_heaper(T  arr_[], size_t t){    return t / sizeof(T); }
#define _countof(a) _countof_heaper(a, sizeof(a))
#endif
enum QXProId {
		OPACITY = 0,
		VISIBLE = 1,
		MAXIMIZED = 2,
		MINIMIZED = 3,
		ENABLED = 4,
		MINIMUMHEIGHT = 5,
		ACTIVED = 6,
		MAXIMUMHEIGHT = 7,
		MINIMUMWIDTH = 8,
		MAXIMUMWIDTH = 9,
		WIDTH = 10,
		HEIGHT = 11,
		FULLSCREEN = 12,
		HIDDEN = 13,
		MODAL = 14,
		WINDOW = 15,
		RESIZE = 16,
		SCROLL = 17,
		FIXEDHEIGHT = 18,
		FIXEDSIZE = 19,
		FIXEDWIDTH = 20,
		PALETTE = 21,
		STYLE = 22,
		CLOSE = 23,
		HIDE = 24,
		LOWER = 25,
		RAISE = 26,
		UPDATE = 27,
		WINDOWTITLE = 28,
		SHOW = 29,
		SHOWFULLSCREEN = 30,
		SHOWMAX = 31,
		SHOWMIN = 32,
		SHOWNORMAL = 33,
		FLATING = 34,
		TITLEBAR = 35,
		DOCKWIDGETFEATURE = 36,
		REPAINT = 37,
		SCICMD = 38,
		SCIFONT = 39,
		FONTSETFAMILY = 40,
		FONTPTSIZE = 41,
		FONTPXSIZE = 42,
		FONTCTOR = 43,
		MENUBAR = 44,
		ADDACTION = 45,
		ADDMENU = 46,
		ADDSEP = 47,
		INSSEP = 48,
		INSMENU = 49,
		MENUBAR_CLR = 50,
		ISDEFUP = 51,
		ISNAMBR = 52,
		SETMENU = 53,
		SETSEP = 54,
		ISSEP = 55,
		SETSHRCUT = 56,
		SETTEXT = 57,
		GETTEXT = 58,
		GETMENU = 59,
		PARENTWIDGET = 60,
		TRIGGER = 61,
		CHECKED = 62,
		ADDACT = 63,
		MDIMODE = 64,
		X_POS = 65,
		Y_POS = 66,
		MOVE = 67,
		SETWIDGET = 68,
		GETWIDGET = 69,
		SUBSETWIDGET = 70,
		SUBGETWIDGET = 71,
		MDISETSCROLLH = 72,
		MDISETSCROLLV = 73,
		CENTRALWIDGET = 74,
		TREEWIDGETADD = 75,
		TREEWIDGETINST = 76,
		TREEWIDGETGETSEL = 77,
		OPEN = 78,
		SAVE = 79,
		SETITEMTEXT = 80,
		SETITEMCOLOR = 81,
		SETBACKCOLOR = 82,
		SETCOLUMNS = 83,
		TREEWIDGETCLEAR = 84,
		SETCOLUMBWIDTH = 85,
		SETTAG = 86,
		GETTAG = 87,
		XNOTIFY = 88,
		NATIVEFINALIZE = 89,
		FOLDER = 90,
		LINEEDITSETTEXT = 91,
		LINEEDITGETTEXT = 92,
		QSCIGETTEXT = 93,
		QSCIGETSELTXT = 94,
		REMSUBWIN = 95,
		ADDSUBWIN = 96,
		MESSAGEBOXWAR = 97,
		MESSAGEBOXERR = 98,
		MESSAGEBOXINF = 99,
		MESSAGEBOXABT = 100,
		MESSAGEBOXQUE = 101,
		CURRENTSUBWIN = 102,
		WINDOWFLAG = 103,
		SETWINDOWFLAG = 104,
		CASCADESUBWIN = 105,
		TILESUBWIN = 106,
		SETACTSUBWIN = 107,
		SCIFINDFIRST = 108,
		COMBOGETTEXT = 109,
		COMBOSETTEXT = 110,
		SCIFINDNEXT = 111,
		PROPADDPROPERTY = 112,
		ADDPROPERTY = 113,
		SETMGRFACTORY = 114,
		SPWVM = 115,
		SRID = 116,
		ADDSUBPROPERTY = 117,
		PROPSETENUM = 118,
		PEORENUMVALUE = 119,
		PROPSETARRT = 120,
		PROPSETARRTSZMAX = 121,
		PROPSETARRTSZMIN = 122,
		PROPSETARRTPTMAX = 123,

		PROPSETARRTPTMIN = 124,
		PROPSETARRTRC = 125,
		PROPSETVALUEPT = 126,
		PROPSETVALUESZ = 127,
		PROPSETVALUERC = 128,
		PROPATTRCONST = 129,
		PROPATTRSSTEP = 130,
		PROPATTRDECIM = 131,
		PROPATTRENUMI = 132,
		PROPATTRENUMN = 133,
		PROPATTRFLAGN = 134,
		PROPATTRMAXIM = 135,
		PROPATTRMINIM = 136,
		PROPATTRREGEX = 137,
		PROPATTRECHOM = 138,
		PROPSETVALUE = 139,
		PROPADDPROPERTYGROUP = 140,
		PROPADDPROPERTYENUM = 141,
		PROPADDPROPERTYFLAG = 142,
		TREEPROPCLEAR = 143,
		PROPGETVALUE = 144,
		COMBOBOXADD = 145,
		COMBOBOXSETID = 146,
		COMBOBOXGETID = 147,
		SETFOCUS = 148,
		TRGETITEMTEXT = 149,
		QSCIGETRANGE = 150,
		LBLSETTEXT = 151,
		LBLGETTEXT = 152,
		CHKSETCHECK = 153,
		CHKGETCHECK = 154,
		GETVIEWPORT = 155,
		ADDDEFACTION = 156,
		SETCONTEXTMENUPOLICY = 157,
		ACTSETTEXT = 158,
		ACTGETTEXT = 159,
		ACTENABLED = 160,
		TREEWIDGETREM = 161,
		WINDOWICON = 162,
		ADDWIDGET = 163,
		INSERTWIDGET = 164,
		ADDPERWIDGET = 165,
		INSERTPERWIDGET = 166,
		REMOVEWIDGET = 167,
		SIZEGRIPENABLED = 168,
		CURRENTMESSAGE = 169,
		STATUSBAR = 170,
		SHOWMESSAGE = 171,
		QPMININUM = 172,
		QPMAXINUM = 173,
		QPVALUE = 174,
		QPTEXT = 175,
		QPVISIBLE = 176,
		QPALIGN = 177,
		QPORIENTATION = 178,
		QPINVERTAPPEAR = 179,
		QPTEXTDIR = 180,
		QPFORMAT = 181,
		QPRESET = 182,
		QPRANGE = 183,
		STYLESHEET = 184,
		PALETTECOLOR = 185,
		TRCOLUMNSHOW = 186,
		TRSELECTMODE = 187,
		TRAUTORESIZE = 188,
		TRHEADERWIDTH = 189,
		TRSORTENABLE = 190,
		TRELIDMODE = 191,
		TREESETCURITEM = 192,
		TREEGETCURROW = 193,
		TREEGETCURCOL = 194,
		TREESETCURROW = 195,
		TREESETCURCOL = 196,
		TREEGETCOUNT = 197,
		TREEGETSELITEM = 198,
		TREEITEMFLAG = 199,
		TREEITEMGETFLAG = 200,
		TREEITEMPARENT = 201,
		DELLOCBUFFER = 202,
		BUFFERSETDATA = 203,
		OPENBUFFER = 204,
		DELLOCICON = 205,
		DELLOCBYTEARRAY = 206,
		SAVESTATE = 207,
		LOADSTATE = 208,
		TRSCROLLBOTTOM = 209,
		TRIEMCLEARCHILD = 210,
		TRIEMSETEXPAND = 211,
		TRIEMSETHIDDEN = 212,
		MAPPOINT = 213,
		TRITEMSETCHECK = 214,
		TRITEMGETCHECK = 215,
		TREEGETCHILDREN = 216,
		SETITEMICON = 217,
		SETPEN = 218,
		SETBRUSH = 219,
		QXPAINTDRAWLINE = 220,
		SETBKBRUSH = 221,
		QXPAINTOPACITY = 222,
		QXPAINTBGMMODE = 223,
		IMGLOAD = 224,
		DELETEIMAGE = 225,
		DRAWIMAGE = 226,
		IMGWIDTH = 227,
		IMGHEIGHT = 228,
		IMGFORMAT = 229,
		IMGGETDATA = 230,
		QXPAINTDRAWRECT = 231,
		FILLRECT = 232,
		DRAWTEXT = 233,
		PAINTERSETFONT = 234,
		LOADFONT = 235,
		SETAPPFONT = 236,
		MATRIXDTOR = 237,
		PAINTERSAVE = 238,
		PAINTERRESTORE = 239,
		PAINTRESETMATRIX = 240,
		PAINTRESETTRANSFORM = 241,
		MATRIXMAPPOINT = 242,
		MATRIXTRANSLATE = 243,
		MATRIXSCALE = 244,
		MATRIXSHEAR = 245,
		MATRIXROTATE = 246,
		MATRIXMUL = 247,
		PAINTERGETMATRIX = 248,
		PAINTSETMATRIX = 249,
		COMBOXCLR = 250,
		BUTTONSETTEXT = 251,
		ROUNDRECT = 252,
		ROUNDEDRECT = 253,
		SETATTRIBUTE = 254,
		SETRENDERHINT = 255,
		MEASURETEXT = 256,
		PAINTERGETFCONT = 257,
		PAINTERFROMIMG = 258,
		DELLOCPAINTER = 259,
		DRAWELLIPSE	=	260,
		SCREENPOSITION = 261,
		SCREENSIZE = 262,
		SCREENCOUNT = 263,
		CURRENTSCREEN = 264,
		DELETEWIDGET = 265,
		TOOLBARADDWIDGET = 266,
		TOOLBARINSWIDGET = 267,
		OPENURL = 268,
		SETSTYLESHEET = 269,
		SETCOMPOSITIONMODE = 270,
		GETSTYLESHEEY = 271,
		FSWADDFILE = 272,
		FSWREMFILE = 273,
		SETCURSOR = 274,
		LOADTRANSLATE = 275,
		OPENLOCAL = 276,
		HASFOCUS = 277,
		GETTOPITEM = 278,
		TREEGETTOPITEMS = 279,
		TABLESETITEM = 280,
		TABLEREMOVEROW = 281,
		TABLEREMOVECOLUMN = 282,
		TABLESETCOLUMNCNT = 283,
		TABLESETROWCNT = 284,
		TABLESELECTROW = 285,
		TABLEITEMFLAG = 286,
		TABLESETTAG = 287,
		TABLEGETTAG = 288,
		TABLESETVHRM = 289,
		TABLESETVHDSS = 290,
		TABLESETSM = 291,
		TABLESETSB = 292,
		TABLESETET = 293,
		TABLESETHHFH = 294,
		TABLESETHHLS = 295,
		TABLESETSG = 296,
		TABLESETVHV = 297,
		TABLESETHHRS = 298,
		SETTABHHCOLUMNS = 299,
		SETTABVHCOLUMNS = 300,
		TABLEGETTEXTBYRC = 301,
		TABLEGETTEXTBYITEM = 302,
		TABLECLEAR = 303,
		TABLECLEARCONTENT = 304,
		TABLEGETSELITEM = 305,
		TABLEGETSELRANGE = 306,
		TABLEGETITEM	=	307,
		SETTABLEITEMTEXT = 308,
		SETTABLEITEMICON = 309,
		SETTABLEITEMCOLOR = 310,
		SETTABLEITEMBACKCOLOR = 311,
		TABITEMGETCHECK = 312,
		TABITEMSETCHECK = 313,
		TABITEMGETFLAG = 314,
		TABLESETCELLWIDGET = 315,
		TABLEGETCELLWIDGET = 316,
		SETFOCUSPOLICY = 317,
		SETWHATSTHIS = 318,
		STYLESHEETSTRING = 319,
		SETSTYLESHEETSTRING = 320,
		GETFONT = 321,
		LOADFONTDESCRIPTION = 322,
		SETWIDGETFONT = 323,
		GETFONTDESCRIPTION = 324,
		GETFONTNAME = 325,
		GETFONTPIXELSIZE = 326,
		GETFONTPTSIZE = 327,
		QPBSETLABELS = 328,
		QPBADJUST = 329,
		QIMGSAVE = 330,
		CHECKABLE = 331,
		SETPROPWIDTHS = 332,
		DELLOCBRUSH = 333,
		SETSPREAD = 334,
		SETCOLORAT = 335,
		DELLOCGRADIENT = 336,
		SETGRADIENT = 337,
		SHOWTOOLTIPS = 338,
		SETTOOLTIPS = 339,
		GETTOOLTIPS = 340,
		PAINTMEASURETEXT = 341,
		PAINTFONTPTSIZE = 342,
		PAINTFONTPXSIZE = 343,
		FONTASCENT = 344,
		FONTDESCENT = 345,
		PAINTFONTASCENT = 346,
		PAINTFONTDESCENT = 347,
		TRSETFOREBR = 348,
		TRSETBACKBR = 349,
		ENABLEDROG = 350,
		PATHMOVETO = 351,
		PATHLINETO = 352,
		PATHARCMOVETO = 353,
		PATHARCTO = 354,
		CUBICTO = 355,
		QUADTO = 356,
		ADDRECT = 357,
		ADDELLIPSE = 358,
		PATHCTOR = 359,
		DRAWPATH = 360,
		UPDATEENABLE = 361,
		OPENMULTI = 362,
		CLIPBOARDTEXT = 363,
		CLIPBOARDIMAGE = 364,
		QSCIDISABLESHORTCUT = 365,
		QSCIUPDATESHORTCUT = 366,
		QSCIUNBINDSHORTCUT = 367,
		OBJECTSETNAME = 368,
		QPB_SETEXPAND = 369,
		QPB_SETSELECT = 370,
		QPB_SETVISIBLE = 371,
		QPB_SETBACKCOLOR = 372,
		ASSOCIATEEXT = 373,
		CHECKASSOCIATED = 374,
		PAINTDEVICEMETRICGET = 375,
		PAINTDEVICEPRFS = 376,
		PRTDLGEXEC = 377,
		PAINTDEVICEMETRICGETPRF = 378,
		PRTDLGDONE = 379,
		PRTDLGSETOPT = 380,
		PRTDLGTEST = 381,
		PRTDLGSETOPTS = 382,
		PRTDLGGETOPTS = 383,
		PAINTERTYPE = 384,
		PAINTDEVICETYPE = 385,
		PAINTDEVICEACTIVE = 386,
		PAINTERFROMDEVICE = 387,
		PVWDLGEXEC = 388,
		PVWDLGDONE = 389,
		PRINTERDTOR = 390,
		PRINTERSETOUTFMT = 391,
		PRINTERGETOUTFMT= 392,
		WIDGETRENDERF = 393,
		WIDGETRENDER4 = 394,
		WIDGETRENDER2 = 395,
		WIDGETRENDER1 = 396,
		PRINTSCIRANGE = 397,
		SCIPRINTERDTOR = 398,
		REGDATASOURCE = 399,
		LOADREPORTFROMFILE = 400,
		LOADREPORTFROMTEXT = 401,
		SHOWREPORT = 402,
		SETDATETIME = 403,
		SETDATE = 404,
		SETTIME = 405,
		GETDATETIME = 406,
		GETDATE = 407,
		GETTIME = 408,
		TESETLINEWRAPMODE = 409,
		TEZOOMOUT = 410, 
		TEZOOMIN = 411,
		TESETAUTOFORMATTING = 412,
		TESETALIGNMENT = 413,
		TESETTEXTBACKGROUNDCOLOR = 414,
		TESETTEXTCOLOR = 415, 
		TESETFONTWEIGHT = 416,
		TESETWORDWRAPMODE = 417,
		TETABCHANGESFOCUS = 418,
		TEGETREADONLY = 419,
		TESETFONTPOINTSIZE = 420,
		TESETTABCHANGESFOCUS = 421,
		TESETFONTITALIC = 422,
		TESETFONTUNDERLINE = 423,
		TESETREADONLY = 424,
		TEGETAUTOFORMATTING = 425,
		TEGETWRAPMODE = 426,
		TEGETALIGNMENT = 427,
		TESETCURRENTFONT = 428,
		TESCROLLTOANCHOR = 429,
		TEAPPEND = 430,
		TEINSERTHTML = 431,
		TEINSERTPLAINTEXT = 432,
		TESETPLACEHOLDERTEXT = 433,
		TESETTEXT = 434,
		TESETHTML = 435,
		TESETPLAINTEXT = 436,
		TESETFONTFAMILY = 437,
		TESELECTALL = 438,
		TECLEAR = 439,
		TEREDO = 440,
		TEUNDO = 441,
		TEPASTE = 442,
		TECOPY = 443,
		TECUT = 444,
		TEGETPLACEHOLDERTEXT = 445,
		TETOPLAINTEXT = 446,
		TETOHTML = 447,
		SETSTYLE = 448,
		TREEITEMISEXPAND = 449,
		TREEITEMSELED = 450,
		SCI_PROP = 451,
		ADDDOCKWIDGET = 452,
		SETDOCKNESTINGENABLED = 453,
		TABIFYDOCKWIDGET = 454,
		ISDOCKNESTINGENABLED = 455,
		LAYTOUADDWIDGET = 456,
		SETLAYOUT = 457,
		DOCKSETALLOWEDAREAS = 458,
		BUTTONGETTEXT = 459,
		WIDGETGETTITLE = 460,
		SLD_SETMIN = 461,
		SLD_GETMIN = 462,
		SLD_SETMAX = 463,
		SLD_GETMAX = 464,
		SLD_SETSINGLESTEP = 465,
		SLD_GETSINGLESTEP = 466,
		SLD_SETPAGESTEP = 467,
		SLD_GETPAGESTEP = 468,
		SLD_SETTRACKING = 469,
		SLD_GETTRACKING = 470,
		SLD_SETSLIDDOWN = 471,
		SLD_GETSLIDDOWN = 472,
		SLD_SETSLIDPOS = 473,
		SLD_GETSLIDPOS = 474,
		SLD_SETINVERTEDAPPEARANCE = 475,
		SLD_GETINVERTEDAPPEARANCE = 476,
		SLD_SETINVERTEDCONTROLS = 477,
		SLD_GETINVERTEDCONTROLS = 478,
		SLD_SETVALUE = 479,
		SLD_GETVALUE = 480,
		SLD_SETORIENTATION = 481,
		SLD_TRIGGERACTION = 482,
		SLD_SETRANGE = 483,
		TOOLBARADDACTION = 484,
		TOOLBARADDSEPAR = 485,
		TOOLBARINSACTION = 486,
		TOOLBARINSSEPAR = 487,
		MAINWNDADDMENU = 488,
		TOOLBARREMACTION = 489,
		MAINWNDADDTOOLBAR = 490,
		MAINWNDMENUADD = 491,
		MENUINSMENU = 492,
		MENUACTION = 493,
		MENUBARINSMENU = 494,
		MENUADDSEPAR = 495,
		MENUBARADDSEPAR = 496,
		SETICONSIZE = 497,
		TABWIDGETADDTAB = 498,
		TABWIDGETINSERTTAB = 499,
		TABWIDGETINSERTTAB2 = 500,
		TABWIDGETREMOVETAB = 501,
		TABWIDGETISTABENABLED = 502,
		TABWIDGETSETTABENABLED = 503,
		TABWIDGETTABTEXT = 504,
		TABWIDGETSETTABTEXT = 505,
		TABWIDGETSETTABICON = 506,
		TABWIDGETSETTABTOOLTIP = 507,
		TABWIDGETTABTOOLTIP = 508,
		TABWIDGETSETTABWHATSTHIS = 509,
		TABWIDGETTABWHATSTHIS = 510,
		TABWIDGETCURRENTINDEX = 511,
		TABWIDGETCURRENTWIDGET = 512,
		TABWIDGETWIDGET = 513,
		TABWIDGETINDEXOF = 514,
		TABWIDGETCOUNT = 515,
		TABWIDGETTABPOSITION = 516,
		TABWIDGETSETTABPOSITION = 517,
		TABWIDGETTABSCLOSABLE = 518,
		TABWIDGETSETTABSCLOSABLE = 519,
		TABWIDGETISMOVABLE = 520,
		TABWIDGETSETMOVABLE = 521,
		TABWIDGETTABSHAPE = 522,
		TABWIDGETSETTABSHAPE = 523,
		TABWIDGETSIZEHINT = 524,
		TABWIDGETMINIMUMSIZEHINT = 525,
		TABWIDGETHEIGHTFORWIDTH = 526,
		TABWIDGETHASHEIGHTFORWIDTH = 527,
		TABWIDGETSETCORNERWIDGET = 528,
		TABWIDGETCORNERWIDGET = 529,
		TABWIDGETELIDEMODE = 530,
		TABWIDGETSETELIDEMODE = 531,
		TABWIDGETICONSIZE = 532,
		TABWIDGETSETICONSIZE = 533,
		TABWIDGETUSESSCROLLBUTTONS = 534,
		TABWIDGETSETUSESSCROLLBUTTONS = 535,
		TABWIDGETDOCUMENTMODE = 536,
		TABWIDGETSETDOCUMENTMODE = 537,
		TABWIDGETAUTOHIDE = 538,
		TABWIDGETSETTABBARAUTOHIDE = 539,
		TABWIDGETCLEAR = 540,
		TABWIDGETTABBAR = 541,
		TABWIDGETSETCURRENTINDEX = 542,
		TABWIDGETSETCURRENTWIDGET = 543,
		TABBARSHAPE = 544,
		TABBARSETSHAPE = 545,
		TABBARADDTAB = 546,
		TABBARINSERTTAB = 547,
		TABBARREMOVETAB = 548,
		TABBARMOVETAB = 549,
		TABBARISTABENABLED = 550,
		TABBARSETTABENABLED = 551,
		TABBARTABTEXT = 552,
		TABBARSETTABTEXT = 553,
		TABBARTABTEXTCOLOR = 554,
		TABBARSETTABTEXTCOLOR = 555,
		TABBARSETTABICON = 556,
		TABBARELIDEMODE = 557,
		TABBARSETELIDEMODE = 558,
		TABBARSETTABTOOLTIP = 559,
		TABBARTABTOOLTIP = 560,
		TABBARSETTABWHATSTHIS = 561,
		TABBARTABWHATSTHIS = 562,
		TABBARTABAT = 563,
		TABBARCURRENTINDEX = 564,
		TABBARCOUNT = 565,
		TABBARSIZEHINT = 566,
		TABBARMINIMUMSIZEHINT = 567,
		TABBARSETDRAWBASE = 568,
		TABBARDRAWBASE = 569,
		TABBARICONSIZE = 570,
		TABBARSETICONSIZE = 571,
		TABBARUSESSCROLLBUTTONS = 572,
		TABBARUSEBUTTONS = 573,
		TABBARTABSCLOSABLE = 574,
		TABBARSETTABSCLOSABLE = 575,
		TABBARSETTABBUTTON = 576,
		TABBARTABBUTTON = 577,
		TABBARSELECTIONBEHAVIORONREMOVE = 578,
		TABBARSETSELECTIONBEHAVIORONREMOVE = 579,
		TABBAREXPANDING = 580,
		TABBARSETEXPANDING = 581,
		TABBARISMOVABLE = 582,
		TABBARSETMOVABLE = 583,
		TABBARDOCUMENTMODE = 584,
		TABBARSETDOCUMENTMODE = 585,
		TABBARAUTOHIDE = 586,
		TABBARSETAUTOHIDE = 587,
		TABBARCHANGECURRENTONDRAG = 588,
		TABBARSETCHANGECURRENTONDRAG = 589,
		TABBARACCESSIBLETABNAME = 590,
		TABBARSETACCESSIBLETABNAME = 591,
		TABBARSETCURRENTINDEX = 592,
		APPLICATIONATTRIBUTES = 593,
		BOXADDSTRETCH = 594,
		BOXADDSPACING = 595,
		BOXSETSPACING = 596,
		BOXSETSTRETCH = 597,
		QCW_SETSELECTEDDATE = 598,
		QCW_SETGRIDVISIBLE = 599,
		QCW_SETNAVIGATIONBARVISIBLE = 600,
		QCW_SETDATERANGE = 601,
		QCW_SETCURRENTPAGE = 602,
		QCW_SHOWNEXTMONTH = 603,
		QCW_SHOWPREVIOUSMONTH = 604,
		QCW_SHOWNEXTYEAR = 605,
		QCW_SHOWPREVIOUSYEAR = 606,
		QCW_SHOWSELECTEDDATE = 607,
		QCW_SHOWTODAY = 608,
		QSTI_VISIBLE = 609,
		QSTI_SETVISIBLE = 610,
		QSTI_SETICON = 611,
		QSTI_GETICON = 612,
		QSTI_SETCONTEXTMENU = 613,
		QSTI_GETCONTEXTMENU = 614,
		QSTI_TOOLTIP = 615,
		QSTI_SETTOOLTIP = 616,
		QSTI_ISSYSTEMTRAYAVAILABLE = 617,
		QSTI_SUPPORTSMESSAGES = 618,
		QSTI_SHOWMESSAGE = 619,
		QH_ORIENTATION = 620,
		QH_GETOFFSET = 621,
		QH_GETLENGTH = 622,
		QH_SECTIONSMOVABLE = 623,
		QH_SECTIONSIZEHINT = 624,
		QH_VISUALINDEXAT = 625,
		QH_LOGICALINDEXAT = 626,
		QH_LOGICALINDEXATXY = 627,
		QH_SECTIONSIZE = 628,
		QH_SECTIONPOSITION = 629,
		QH_SECTIONVIEWPORTPOSITION = 630,
		QH_MOVESECTION = 631,
		QH_SWAPSECTIONS = 632,
		QH_RESIZESECTION = 633,
		QH_RESIZESECTIONS = 634,
		QH_ISSECTIONHIDDEN = 635,
		QH_SETSECTIONHIDDEN = 636,
		QH_HIDDENSECTIONCOUNT = 637,
		QH_HIDESECTION = 638,
		QH_SHOWSECTION = 639,
		QH_COUNT = 640,
		QH_VISUALINDEX = 641,
		QH_LOGICALINDEX = 642,
		QH_SETSECTIONSMOVABLE = 643,
		QH_SETSECTIONSCLICKABLE = 644,
		QH_SECTIONSCLICKABLE = 645,
		QH_SETHIGHLIGHTSECTIONS = 646,
		QH_HIGHLIGHTSECTIONS = 647,
		QH_SECTIONRESIZEMODE = 648,
		QH_SETSECTIONRESIZEMODE = 649,
		QH_SETRESIZECONTENTSPRECISION = 650,
		QH_RESIZECONTENTSPRECISION = 651,
		QH_STRETCHSECTIONCOUNT = 652,
		QH_SETSORTINDICATORSHOWN = 653,
		QH_ISSORTINDICATORSHOWN = 654,
		QH_SETSORTINDICATOR = 655,
		QH_SORTINDICATORORDER = 656,
		QH_STRETCHLASTSECTION = 657,
		QH_SETSTRETCHLASTSECTION = 658,
		QH_CASCADINGSECTIONRESIZES = 659,
		QH_SETCASCADINGSECTIONRESIZES = 660,
		QH_DEFAULTSECTIONSIZE = 661,
		QH_SETDEFAULTSECTIONSIZE = 662,
		QH_RESETDEFAULTSECTIONSIZE = 663,
		QH_MINIMUMSECTIONSIZE = 664,
		QH_SETMINIMUMSECTIONSIZE = 665,
		QH_MAXIMUMSECTIONSIZE = 666,
		QH_SETMAXIMUMSECTIONSIZE = 667,
		QH_DEFAULTALIGNMENT = 668,
		QH_SETDEFAULTALIGNMENT = 669,
		QH_DOITEMSLAYOUT = 670,
		QH_SECTIONSMOVED = 671,
		QH_SECTIONSHIDDEN = 672,
		QH_SAVESTATE = 673,
		QH_LOADSTATE = 674,
		QH_RESET = 675,
		QH_SORTINDICATORSECTION = 676,
		QTW_HORIZONTALHEADER = 677,
		QTW_VERTICALHEADER = 678,
		QTV_ROWVIEWPORTPOSITION = 679,
		QTV_ROWAT = 680,
		QTV_SETROWHEIGHT = 681,
		QTV_ROWHEIGHT = 682,
		QTV_COLUMNVIEWPORTPOSITION = 683,
		QTV_COLUMNAT = 684,
		QTV_SETCOLUMNWIDTH = 685,
		QTV_COLUMNWIDTH = 686,
		QTV_ISROWHIDDEN = 687,
		QTV_SETROWHIDDEN = 688,
		QTV_ISCOLUMNHIDDEN = 689,
		QTV_SETCOLUMNHIDDEN = 690,
		QTV_SETSORTINGENABLED = 691,
		QTV_ISSORTINGENABLED = 692,
		QTV_SHOWGRID = 693,
		QTV_GRIDSTYLE = 694,
		QTV_SETGRIDSTYLE = 695,
		QTV_SETWORDWRAP = 696,
		QTV_WORDWRAP = 697,
		QTV_SETCORNERBUTTONENABLED = 698,
		QTV_ISCORNERBUTTONENABLED = 699,
		QTV_SETSPAN = 700,
		QTV_ROWSPAN = 701,
		QTV_COLUMNSPAN = 702,
		QTV_CLEARSPANS = 703,
		QTV_SORTBYCOLUMN = 704,
		QW_SETICON = 705,
		QLAYOUT_SETCONTENTSMARGINS = 706,
		QLAYOUT_SETMARGIN = 707,
		QLABEL_SETALIGNMENT = 708,
		QLABEL_GETALIGNMENT = 709,
		QTNTITLEBAR = 710,
		QTNTITLEBARWIDGET = 711,
		QTNMENUBAR = 712,
		QTNSTATUSBAR = 713,
		QTNCENTRALWIDGET = 714,
		QTNDOCKBARMANAGER = 715,
		QTNDOCKPANELMANAGER = 716,
		QTNADDTOOLBAR = 717,
		QTNINSERTDOCKBAR = 718,
		QTNREMOVEDOCKBAR = 719,
		QTNMOVEDOCKBAR = 720,
		QTNCLEARDOCKBARS = 721,
		QTNADDDOCUMENTPANEL = 722,
		QTNINSERTDOCUMENTPANEL = 723,
		QTNREMOVEDOCKPANEL = 724,
		QTNCLEARDOCKPANELS = 725,
		QTNADDDOCKWINDOW = 726,
		QTNADDDOCKPANEL = 727,
		QTNADDDOCKPANELS = 728,
		QTNWT_SETVISIBLE = 729,
		QTNWT_SETQWIZARDSUPPORTS = 730,
		QTNWT_SETSYSMENUBUTTONVISIBLE = 731,
		QTNWT_SETEXTENDVIEWINTOTITLEBAR = 732,
		QTNWT_SETBLURBEHINDWINDOWENABLED = 733,
		QTNWT_SETSTYLEDFRAME = 734,
		QTNWT_ISQWIZARDSUPPORTS = 735,
		QTNWT_ISSYSMENUBUTTONVISIBLE = 736,
		QTNWT_EXTENDVIEWINTOTITLEBAR = 737,
		QTNWT_BLURBEHINDWINDOWENABLED = 738,
		QTNWT_STYLEDFRAME = 739,
		QTNWT_ISVISIBLE = 740,
		QTNWT_SHOWHELP = 741,
		QTNWT_BACKREQUESTED = 742,
		QTNWT_REMOVEANDDELETE = 743,
		QTNWT_SHOW = 744,
		QTNWT_HIDE = 745,
		QTNWT_UPDATE = 746,
		QTNWT_SETWIDGET = 747,
		QTNWT_SETBACKGROUNDCOLOR = 748,
		QTNWT_SETBORDERTHICKNESS = 749,
		QTNWT_SETSYSBUTTONKIND = 750,
		QTNWT_SETTITLEHEIGHT = 751,
		QTNWT_WIDGET = 752,
		QTNWT_FRAMECOLOR = 753,
		QTNWT_BACKGROUNDCOLOR = 754,
		QTNWT_SYSBUTTONKIND = 755,
		QTNWT_BORDERTHICKNESS = 756,
		QTNWT_TITLEHEIGHT = 757,
		QTNDB_CENTRALWIDGET = 758,
		QTNDB_MANAGEDWIDGET = 759,
		QTNDB_DOCKBARCOUNT = 760,
		QTNDB_SETCENTRALWIDGET = 761,
		QTNDB_REMOVEDOCKBAR = 762,
		QTNDB_CLEARDOCKBARS = 763,
		QTNDB_ADDTOOLBAR = 764,
		QTNDB_INSERTDOCKBAR = 765,
		QTNDB_MOVEDOCKBAR = 766,
		QTNQPM_MANAGEDWIDGET = 767,
		QTNQPM_LAYOUTPANEL = 768,
		QTNQPM_CENTRALLAYOUTPANEL = 769,
		QTNQPM_ACTIVEDOCKPANEL = 770,
		QTNQPM_CENTRALWIDGET = 771,
		QTNQPM_ADDDOCKWINDOW = 772,
		QTNQPM_ADDDOCUMENTPANEL = 773,
		QTNQPM_INSERTDOCUMENTPANEL = 774,
		QTNQPM_ADDDOCKPANEL = 775,
		QTNQPM_ADDDOCKPANELS = 776,
		QTNQPM_REMOVEDOCKPANEL = 777,
		QTNQPM_CLEARDOCKPANELS = 778,
		QTNQPM_ISDOCKPANELFLOAT = 779,
		QTNQPM_SETDOCKPANELFLOAT = 780,
		QTNQPM_SHOWDOCKPANEL = 781,
		QTNQPM_SETDOCKPANELAUTOHIDE = 782,
		QTNQPM_ISDOCKPANELCLOSED = 783,
		QTNQPM_ISDOCKPANELAUTOHIDE = 784,
		QTNQPM_CLOSEDOCKPANEL = 785,
		QTNQPM_SETCENTRALWIDGET = 786,
		QTNQPM_MARGIN = 787,
		QTNQPM_DEFAULTPANEFEATURES = 788,
		QTNQPM_SETMARGIN = 789,
		QTNQPM_DOCKWINDOWTITLE = 790,
		QTNQPM_SETDOCKWINDOWTITLE = 791,
		QTNQPM_ISDOCKPANELFULLCONTENTSWHILEDRAGGINGSHOWN = 792,
		QTNQPM_ISDOCKPANELTRANSPARENTWHILEDRAGGING = 793,
		QTNQPM_ISARROWMARKERSSHOWN = 794,
		QTNQPM_ENDUPDATE = 795,
		QTNQPM_BEGINUPDATE = 796,
		QTNQPM_BESTFIT = 797,
		QTNQPM_SETARROWMARKERSSHOWN = 798,
		QTNQPM_SETDOCKPANELTRANSPARENTWHILEDRAGGING = 799,
		QTNQPM_SETDOCKPANELFULLCONTENTSWHILEDRAGGINGSHOWN = 800,
		QTNQPM_SETDEFAULTPANEFEATURES = 801,
		QTNDW_FINALIZATIONWINDOW = 802,
		QTNDW_LAYOUTPANEL = 803,
		QTNDW_DOCKMANAGER = 804,
		QTNDW_INITIALIZATIONWINDOW = 805,
		QTNDPB_DOCKMANAGER = 806,
		QTNDPB_PARENTPANEL = 807,
		QTNDPB_TOPDOCKWINDOW = 808,
		QTNDPB_DOCKWINDOW = 809,
		QTNDPB_SETDOCKWINDOW = 810,
		QTNDPB_SETPARENTPANEL = 811,
		QTNDWP_SETFEATURES = 812,
		QTNDWP_SETALLOWEDAREAS = 813,
		QTNDWP_ISAREAALLOWED = 814,
		QTNDWP_ISVALID = 815,
		QTNDWP_SHOWPANEL = 816,
		QTNDWP_ISCLOSED = 817,
		QTNDWP_CLOSEPANEL = 818,
		QTNDWP_ISAUTOHIDE = 819,
		QTNDWP_ISACTIVE = 820,
		QTNDWP_ACTIVATE = 821,
		QTNDWP_DEACTIVATE = 822,
		QTNDWP_ISFLOAT = 823,
		QTNDWP_WIDGET = 824,
		QTNDWP_MENUBUTTON = 825,
		QTNDWP_VISIBLEACTION = 826,
		QTNDWP_TITLEBAR = 827,
		QTNDWP_SETAUTOHIDE = 828,
		QTNDWP_SETFLOAT = 829,
		QTNDWP_FEATURES = 830,
		QTNDWP_ALLOWEDAREAS = 831,
		QTNDWP_SETWIDGET = 832,
		QTNDWP_SETICON = 833,
		QTNDWP_SETMENUBUTTON = 834,
		QTNDWP_SETTITLEBAR = 835,
		QTNDWP_SETPARENTPANEL = 836,
		QTNDWP_SETCAPTION = 837,
		QTNDWP_CAPTION = 838,
		QTNDDP_SETWIDGET = 839,
		QTNDLP_ISEMPTY = 840,
		QTNDLP_CHILDCOUNT = 841,
		QTNDLP_LAYOUTTYPE = 842,
		QTNDPM_INSERTDOCKPANEL = 843,
		QTNDMW_INSERTDOCKPANEL = 844,
		QTAPP_SETSTYLE = 845,
		QTNDS_THEME = 846,
		QTNDS_SETTHEME = 847,
		QTNWTB_GET = 848,
		QTNWTB_FIND = 849,
		QSCI_ENABLESCROLLBARMARKER = 850,
		QSCI_SETSCROLLBARMARKER = 851,
		QTMW_SETCENTRALWIDGET = 852,
		DBMSAVESTATE = 853,
		DPMSAVESTATE = 854,
		DBMLOADSTATE = 855,
		DPMLOADSTATE = 856,
		DMLOADSTATE = 857,
		DMSAVESTATE = 858,
		QMEDIAOBJECT_SETNOTIFYINTERVAL = 859,
		QMEDIAOBJECT_ISMETADATAAVAILABLE = 860,
		QMEDIAOBJECT_ISAVAILABLE = 861,
		QMEDIAOBJECT_SERVICE = 862,
		QMEDIAOBJECT_NOTIFYINTERVAL = 863,
		QMEDIAOBJECT_AVAILABILITY = 864,
		QMEDIAOBJECT_UNBIND = 865,
		QMEDIAOBJECT_BIND = 866,
		QMEDIAPLAYER_SETVOLUME = 867,
		QMEDIAPLAYER_SETAUDIOROLE = 868,
		QMEDIAPLAYER_ISVIDEOAVAILABLE = 869,
		QMEDIAPLAYER_ISAUDIOAVAILABLE = 870,
		QMEDIAPLAYER_ISMUTED = 871,
		QMEDIAPLAYER_SUPPORTEDAUDIOROLES = 872,
		QMEDIAPLAYER_PLAYBACKRATE = 873,
		QMEDIAPLAYER_SETPLAYBACKRATE = 874,
		QMEDIAPLAYER_SETMUTED = 875,
		QMEDIAPLAYER_AUDIOROLE = 876,
		QMEDIAPLAYER_AVAILABILITY = 877,
		QMEDIAPLAYER_ERROR = 878,
		QMEDIAPLAYER_ISSEEKABLE = 879,
		QMEDIAPLAYER_BUFFERSTATUS = 880,
		QMEDIAPLAYER_VOLUME = 881,
		QMEDIAPLAYER_MEDIASTATUS = 882,
		QMEDIAPLAYER_STATE = 883,
		QMEDIAPLAYER_SETPOSITION = 884,
		QMEDIAPLAYER_STOP = 885,
		QMEDIAPLAYER_PAUSE = 886,
		QMEDIAPLAYER_PLAY = 887,
		QMEDIAPLAYER_SETVIDEOOUTPUT = 888,
		QMEDIAPLAYER_ERRORSTRING = 889,
		QMEDIAPLAYER_SUPPORTEDMIMETYPES = 890,
		QMEDIAPLAYER_HASSUPPORT = 891,
		QMEDIAPLAYER_POSITION = 892,
		QMEDIAPLAYER_DURATION = 893,
		QMEDIAPLAYER_SETMEDIA = 894,
		QVIDEOWIDGET_SETSATURATION = 895,
		QVIDEOWIDGET_SETHUE = 896,
		QVIDEOWIDGET_SETCONTRAST = 897,
		QVIDEOWIDGET_SETBRIGHTNESS = 898,
		QVIDEOWIDGET_SETASPECTRATIOMODE = 899,
		QVIDEOWIDGET_MEDIAOBJECT = 900,
		QVIDEOWIDGET_SETFULLSCREEN = 901,
		QVIDEOWIDGET_SATURATION = 902,
		QVIDEOWIDGET_HUE = 903,
		QVIDEOWIDGET_CONTRAST = 904,
		QVIDEOWIDGET_BRIGHTNESS = 905,
		QVIDEOWIDGET_ASPECTRATIOMODE = 906,
		QVIDEOWIDGET_SIZEHINT = 907,
		QAUDIOFORMAT_SETSAMPLETYPE = 908,
		QAUDIOFORMAT_SETBYTEORDER = 909,
		QAUDIOFORMAT_SETSAMPLESIZE = 910,
		QAUDIOFORMAT_SETCHANNELCOUNT = 911,
		QAUDIOFORMAT_SETSAMPLERATE = 912,
		QAUDIOFORMAT_FRAMESFORBYTES = 913,
		QAUDIOFORMAT_BYTESFORFRAMES = 914,
		QAUDIOFORMAT_ISVALID = 915,
		QAUDIOFORMAT_BYTESPERFRAME = 916,
		QAUDIOFORMAT_SAMPLETYPE = 917,
		QAUDIOFORMAT_BYTEORDER = 918,
		QAUDIOFORMAT_SAMPLESIZE = 919,
		QAUDIOFORMAT_CHANNELCOUNT = 920,
		QAUDIOFORMAT_SAMPLERATE = 921,
		QAUDIOFORMAT_SETCODEC = 922,
		QAUDIOFORMAT_FRAMESFORDURATION = 923,
		QAUDIOFORMAT_BYTESFORDURATION = 924,
		QAUDIOFORMAT_CODEC = 925,
		QAUDIOFORMAT_DURATIONFORFRAMES = 926,
		QAUDIOFORMAT_DURATIONFORBYTES = 927,
		QAUDIOOUTPUT_SETNOTIFYINTERVAL = 928,
		QAUDIOOUTPUT_SETBUFFERSIZE = 929,
		QAUDIOOUTPUT_VOLUME = 930,
		QAUDIOOUTPUT_SETVOLUME = 931,
		QAUDIOOUTPUT_STATE = 932,
		QAUDIOOUTPUT_ERROR = 933,
		QAUDIOOUTPUT_NOTIFYINTERVAL = 934,
		QAUDIOOUTPUT_PERIODSIZE = 935,
		QAUDIOOUTPUT_BYTESFREE = 936,
		QAUDIOOUTPUT_BUFFERSIZE = 937,
		QAUDIOOUTPUT_RESUME = 938,
		QAUDIOOUTPUT_SUSPEND = 939,
		QAUDIOOUTPUT_RESET = 940,
		QAUDIOOUTPUT_STOP = 941,
		QAUDIOOUTPUT_START = 942,
		QAUDIOOUTPUT_ELAPSEDUSECS = 943,
		QAUDIOOUTPUT_PROCESSEDUSECS = 944,
		QAUDIOOUTPUT_FORMAT = 945,
		QAUDIOOUTPUT_WRITE = 946,

		QAUDIOINPUT_SETNOTIFYINTERVAL = 947,
		QAUDIOINPUT_SETBUFFERSIZE = 948,
		QAUDIOINPUT_VOLUME = 949,
		QAUDIOINPUT_SETVOLUME = 950,
		QAUDIOINPUT_STATE = 951,
		QAUDIOINPUT_ERROR = 952,
		QAUDIOINPUT_NOTIFYINTERVAL = 953,
		QAUDIOINPUT_PERIODSIZE = 954,
		QAUDIOINPUT_BYTESFREE = 955,
		QAUDIOINPUT_BUFFERSIZE = 956,
		QAUDIOINPUT_RESUME = 957,
		QAUDIOINPUT_SUSPEND = 958,
		QAUDIOINPUT_RESET = 959,
		QAUDIOINPUT_STOP = 960,
		QAUDIOINPUT_START = 961,
		QAUDIOINPUT_ELAPSEDUSECS = 962,
		QAUDIOINPUT_PROCESSEDUSECS = 963,
		QAUDIOINPUT_FORMAT = 964,
		QAUDIOINPUT_READ = 965,
		QAUDIODEVICEINFO_ISNULL = 966,
		QAUDIODEVICEINFO_SUPPORTEDBYTEORDERS = 967,
		QAUDIODEVICEINFO_FINALIZE = 968,
		QAUDIOFORMAT_FINALIZE = 969,
		QAUDIODEVICEINFO_ISFORMATSUPPORTED = 970,
		QAUDIODEVICEINFO_SUPPORTEDSAMPLETYPES = 971,
		QAUDIODEVICEINFO_SUPPORTEDSAMPLESIZES = 972,
		QAUDIODEVICEINFO_SUPPORTEDCHANNELCOUNTS = 973,
		QAUDIODEVICEINFO_SUPPORTEDSAMPLERATES = 974,
		QAUDIODEVICEINFO_SUPPORTEDCODECS = 975,
		QAUDIODEVICEINFO_NAME = 976,
		QAUDIODEVICEINFO_AVAILABLEDEVICES = 977,
		QAUDIODEVICEINFO_DEFAULTOUTPUTDEVICE = 978,
		QAUDIODEVICEINFO_DEFAULTINPUTDEVICE = 979,
		QAUDIODEVICEINFO_PREFERREDFORMAT = 980,
		QAUDIODEVICEINFO_NEARESTFORMAT = 981,
		QOPENGLWIDGET_SETUPDATEBEHAVIOR = 982,
		QOPENGLWIDGET_ISVALID = 983,
		QOPENGLWIDGET_CONTEXT = 984,
		QOPENGLWIDGET_DEFAULTFRAMEBUFFEROBJECT = 985,
		QOPENGLWIDGET_UPDATEBEHAVIOR = 986,
		QOPENGLWIDGET_SETFORMAT = 987,
		QOPENGLWIDGET_DONECURRENT = 988,
		QOPENGLWIDGET_MAKECURRENT = 989,
		QOPENGLWIDGET_GRABFRAMEBUFFER = 990,
		QOPENGLWIDGET_FORMAT = 991,
		QOPENGLCONTEXT_GLOBALSHARECONTEXT = 992,
		QOPENGLCONTEXT_ISOPENGLES = 993,
		QOPENGLCONTEXT_ISVALID = 994,
		QOPENGLCONTEXT_CREATE = 995,
		QOPENGLCONTEXT_SUPPORTSTHREADEDOPENGL = 996,
		QOPENGLCONTEXT_CURRENTCONTEXT = 997,
		QOPENGLCONTEXT_SHARECONTEXT = 998,
		QOPENGLCONTEXT_OPENGLMODULETYPE = 999,
		QOPENGLCONTEXT_DEFAULTFRAMEBUFFEROBJECT = 1000,
		QOPENGLCONTEXT_SETSHARECONTEXT = 1001,
		QOPENGLCONTEXT_SETFORMAT = 1002,
		QOPENGLCONTEXT_DONECURRENT = 1003,
		QOPENGLCONTEXT_EXTRAFUNCTIONS = 1004,
		QOPENGLCONTEXT_FUNCTIONS = 1005,
		QOPENGLCONTEXT_FORMAT = 1006,
		QOPENGLCONTEXT_ARESHARING = 1007,
			QSURFACEFORMAT_SETSWAPINTERVAL = 1008,
			QSURFACEFORMAT_SETOPTIONS = 1009,
			QSURFACEFORMAT_SETMINORVERSION = 1010,
			QSURFACEFORMAT_SETMAJORVERSION = 1011,
			QSURFACEFORMAT_SETRENDERABLETYPE = 1012,
			QSURFACEFORMAT_SETSWAPBEHAVIOR = 1013,
			QSURFACEFORMAT_SETSAMPLES = 1014,
			QSURFACEFORMAT_SETALPHABUFFERSIZE = 1015,
			QSURFACEFORMAT_SETBLUEBUFFERSIZE = 1016,
			QSURFACEFORMAT_SETGREENBUFFERSIZE = 1017,
			QSURFACEFORMAT_SETREDBUFFERSIZE = 1018,
			QSURFACEFORMAT_SETSTENCILBUFFERSIZE = 1019,
			QSURFACEFORMAT_SETDEPTHBUFFERSIZE = 1020,
			QSURFACEFORMAT_TESTOPTION = 1021,
			QSURFACEFORMAT_SETOPTION = 1022,
			QSURFACEFORMAT_STEREO = 1023,
			QSURFACEFORMAT_HASALPHA = 1024,
			QSURFACEFORMAT_SETSTEREO = 1025,
			QSURFACEFORMAT_DEPTHBUFFERSIZE = 1026,
			QSURFACEFORMAT_STENCILBUFFERSIZE = 1027,
			QSURFACEFORMAT_REDBUFFERSIZE = 1028,
			QSURFACEFORMAT_GREENBUFFERSIZE = 1029,
			QSURFACEFORMAT_BLUEBUFFERSIZE = 1030,
			QSURFACEFORMAT_ALPHABUFFERSIZE = 1031,
			QSURFACEFORMAT_SAMPLES = 1032,
			QSURFACEFORMAT_SWAPBEHAVIOR = 1033,
			QSURFACEFORMAT_RENDERABLETYPE = 1034,
			QSURFACEFORMAT_MAJORVERSION = 1035,
			QSURFACEFORMAT_MINORVERSION = 1036,
			QSURFACEFORMAT_OPTIONS = 1037,
			QSURFACEFORMAT_SWAPINTERVAL = 1038,
			QSURFACEFORMAT_SETVERSION = 1039,
			QSURFACEFORMAT_SETDEFAULTFORMAT = 1040,
			QSURFACEFORMAT_DEFAULTFORMAT = 1041,
			QOPENGLFUNCTIONS_HASOPENGLFEATURE = 1042,
			QOPENGLFUNCTIONS_OPENGLFEATURES = 1043,
			QOPENGLFUNCTIONS_INITIALIZEOPENGLFUNCTIONS = 1044,
			QSURFACEFORMAT = 1045,
			QOPENGLFUNCTIONS_1_0_INITIALIZEOPENGLFUNCTIONS = 1046,
			QOPENGLCONTEXT_FUNCTIONS_1_0 = 1047,
			QOPENGLFUNCTIONS_ES2_INITIALIZEOPENGLFUNCTIONS = 1048,
			QOPENGLFUNCTIONS_1_1_INITIALIZEOPENGLFUNCTIONS = 1049,
			QOPENGLCONTEXT_FUNCTIONS_1_1 = 1050,
			QOPENGLCONTEXT_FUNCTIONS_ES2 = 1051,
			QWIDGET_ADJUSTSIZE = 1052,
			QWIDGET_SETCONTENTSMARGINS = 1053
};

extern XNLEnv * gs_env;
XNLEXPORT void nativeFinalize(XObject * xobj);
void installAction(QObject * obj);
class XObjectData{
private:
	XObject * object;
	XObject * tag;
	int reference;
public:

	XObjectData() {
		object = NULL;
		tag = NULL;
		reference = 0;
	}

	bool dereference() {
		return (--reference == 0);
	}

	void increnment() {
		reference++;
	}

	virtual ~XObjectData() {
		detach();
		detachTag();
		
	}

	void detach() {
		if (object != NULL) {
			nativeFinalize(object);
			gs_env->dereferenceObject(object);
			object = NULL;
		}
	}

	void detachTag() {
		if (tag != NULL) {
			gs_env->dereferenceObject(tag);
			tag = NULL;
		}
	}
	void setObject(XObject * obj) {
		detach();

		if (obj != NULL) {
			object = gs_env->referenceObject(obj);
		}
	}
	XObject * getObject() {
		return object;
	}
	XObject * getTag() {
		return tag;
	}
	void setTag(XObject * obj) {
		detachTag();

		if (obj != NULL) {
			tag = gs_env->referenceObject(obj);
		}
	}
};

class XMetaHandle {
	XObjectData * _d;
public:

	XMetaHandle() {
		_d = 0;
	}

	XMetaHandle(XObjectData * d) {
		_d = 0;
		attach(d);
	}

	XMetaHandle(const XMetaHandle & x) {
		_d = 0;
		attach(x._d);
	}

	~XMetaHandle() {
		detach();
	}

	XMetaHandle & operator =(const XMetaHandle & x) {
		attach(x._d);
		return *this;
	}

	void detach() {
		if (_d != 0) {
			if (_d->dereference()) {
				delete _d;
			}
			_d = 0;
		}
	}

	void attach(XObjectData * d) {
		detach();

		_d = d;
		if (_d != 0) {
			_d->increnment();
		}
	}

	bool operator == (const XObjectData *  v)const  {
		return _d == v;
	}
	bool operator != (const XObjectData *  v)const {
		return _d != v;
	}
	const XObjectData *  operator -> ()const {
		return _d;
	}
	XObjectData *  operator -> () {
		return _d;
	}

	XObjectData * ptr() {
		return _d;
	}
};

Q_DECLARE_METATYPE(XMetaHandle);

struct  XIDENT
{
	const char * path;
	int methodId;
};

struct megInfo {
	const char * name;
	int id;
};

extern XIDENT  methods[];

#define TRIGGER_ID		220
#define ITEMPRESS_ID	221
#define ITEMCLK_ID		222
#define ITEMDBCLK_ID	223
#define ITEMACTIVE_ID	224
#define ITEMENTER_ID	225
#define ITEMCHANGE_ID	226
#define ITEMEXPAND_ID	227
#define ITEMCOLLPA_ID	228
#define ITEMCURCHA_ID	229
#define ITEMSELCHA_ID	230
#define NOTIFY_ID		231
#define FINALIZE_ID		232
#define BTNCLICK_ID		233
#define TOGGLE_ID		234
#define ONCHECK_ID		235
#define ONPRESS_ID		236
#define ONRELEASE_ID	237

#define ONFINISH_ID	238
#define ONACCEPT_ID	239
#define ONREJECT_ID	240

#define SCEN_CHANGE_ID  241
#define ON_CALLTIPCLICK_ID  242
#define ON_CHARADDED_ID  243
#define ON_DOUBLECLICK_ID  244
#define ON_DWELLEND_ID  245
#define ON_DWELLSTART_ID  246
#define ON_FOCUSIN_ID  247
#define ON_FOCUSOUT_ID  248
#define ON_HOTSPOTCLICK_ID  249
#define ON_HOTSPOTDOUBLECLICK_ID  250
#define ON_HOTSPOTRELEASECLICK_ID  251
#define ON_INDICATORCLICK_ID  252
#define ON_INDICATORRELEASE_ID  253
#define ON_MACRORECORD_ID  254
#define ON_MARGINCLICK_ID  255
#define ON_MARGINRIGHTCLICK_ID  256
#define ON_MODIFIED_ID  257
#define ON_MODIFYATTEMPTRO_ID  258
#define ON_NEEDSHOWN_ID  259
#define ON_PAINTED_ID  260
#define ON_SAVEPOINTLEFT_ID  261
#define ON_SAVEPOINTREACHED_ID  262
#define ON_STYLENEEDED_ID  263
#define ON_UPDATEUI_ID  264
#define ON_USERLISTSELECTION_ID  265
#define ON_USERLISTSELECTION_ID1  266
#define ON_ZOOM_ID  267
#define ON_SELCHANGED_ID  268 
#define ON_AUTOCCANCELLED_ID 269 
#define ON_AUTOCCHARDELETED_ID 270 
#define ON_AUTOCCOMPLETED_ID 271 
#define ON_AUTOCSELECTION_ID 272 
#define ON_AUTOCSELECTION_ID_1 273 

#define ON_EDITCHANGE 274
#define ON_EDITEDITED 275
#define ON_EDITPOSCHANGE 276
#define ON_EDITRETURN 277
#define ON_EDITFINISH 278
#define ON_EDITSELCHANGE 279
#define ON_CURTEXTCHANGE 280
#define ON_ACTIVATED 281
#define ON_SELCHANGE 282
#define ON_FILECHANGE 283
#define ON_DIRCHANGE 284
#define ON_CELLCHANGE 285
#define ON_CELLITEMCHANGE 286
#define ON_CELLPRESS 287
#define ON_CELLITEMPRESS 288
#define ON_CELLCLICK 289
#define ON_CELLITEMCLICK 290
#define ON_CELLDBCLICK 291
#define ON_CELLITEMDBCLICK 292
#define ON_CELLENTER 293
#define ON_CELLITEMENTER 294
#define ON_CELLACTIVE 295
#define ON_CELLITEMACTIVE 296
#define ON_ENUMCHANGED 297
#define ON_VVALUECHANGE 298
#define ON_VATTRCHANGE 299
#define ON_PRINTVIEWREQUEST 300
#define ON_REPORTRENDERSTARTED		301
#define ON_REPORTRENDERPAGEFINISH	302
#define ON_REPORTRENDERFINISH		303
#define ON_DATASOURCEGETCALLBACKDATA	304
#define ON_DATASOURCECHANGEPOS			305
#define ON_DATETIMECHANGE			306
#define ON_DATECHANGE				307
#define ON_TIMECHANGE				308
#define ON_TEXTEDITCHANGE					309
#define ON_TEXTEDITPOSCHANGE				310
#define ON_TEXTEDITSELCHANGE				311

#define ON_SLIDER_VALUECHANGED	312
#define ON_SLIDER_SLIDERPRESSED	313
#define ON_SLIDER_SLIDERMOVED	314	
#define ON_SLIDER_SLIDERRELEASED	315
#define ON_SLIDER_RANGECHANGED	316
#define ON_SLIDER_ACTIONTRIGGERED	317


#define ON_QTABWIDGET_CURRENTCHANGED 318
#define ON_QTABWIDGET_TABCLOSEREQUESTED	319	
#define ON_QTABWIDGET_TABBARCLICKED	320
#define ON_QTABWIDGET_TABBARDOUBLECLICKED	321


#define ON_QTABBAR_CURRENTCHANGED 322
#define ON_QTABBAR_TABCLOSEREQUESTED	323
#define ON_QTABBAR_TABMOVED	324
#define ON_QTABBAR_TABBARCLICKED	325
#define ON_QTABBAR_TABBARDOUBLECLICKED	326


#define ON_QCW_SELECTIONCHANGED 327
#define ON_QCW_CLICKED 328
#define ON_QCW_ACTIVATED 329
#define ON_QCW_CURRENTPAGECHANGED 330

#define ON_QSTI_ACTIVATED 331
#define ON_QSTI_CLICKED 332

#define ON_QH_SECTIONMOVED	333
#define ON_QH_SECTIONRESIZED	334
#define ON_QH_SECTIONPRESSED	335
#define ON_QH_SECTIONCLICKED	336
#define ON_QH_SECTIONENTERED	337
#define ON_QH_SECTIONDOUBLECLICKED	338
#define ON_QH_SECTIONCOUNTCHANGED	339
#define ON_QH_SECTIONHANDLEDOUBLECLICKED	340
#define ON_QH_GEOMETRIESCHANGED		341
#define ON_QH_SORTINDICATORCHANGED	342

#define ON_QWT_BACKREQUESTED	343
#define ON_QWT_SHOWHELP	344

#define ON_QMediaPlayer_mediaChanged 345
#define ON_QMediaPlayer_currentMediaChanged 346
#define ON_QMediaPlayer_stateChanged 347
#define ON_QMediaPlayer_mediaStatusChanged 348
#define ON_QMediaPlayer_durationChanged 349
#define ON_QMediaPlayer_positionChanged 350
#define ON_QMediaPlayer_volumeChanged 351
#define ON_QMediaPlayer_mutedChanged 352
#define ON_QMediaPlayer_audioAvailableChanged 353
#define ON_QMediaPlayer_videoAvailableChanged 354
#define ON_QMediaPlayer_bufferStatusChanged 355
#define ON_QMediaPlayer_seekableChanged 356
#define ON_QMediaPlayer_playbackRateChanged 357
#define ON_QMediaPlayer_audioRoleChanged 358
#define ON_QMediaPlayer_error 359

#define ON_QMediaObject_notifyIntervalChanged 360
#define ON_QMediaObject_metaDataAvailableChanged 361
#define ON_QMediaObject_metaDataChanged 362
#define ON_QMediaObject_availabilityChanged 363
#define ON_QMediaObject_availabilityChanged1 364


#define QVideoWidget_fullScreenChanged 365
#define QVideoWidget_brightnessChanged 366
#define QVideoWidget_contrastChanged 367
#define QVideoWidget_hueChanged 368
#define QVideoWidget_saturationChanged 369 

#define QAudioOutput_stateChanged 370
#define QAudioOutput_notify 371

#define QAudioInput_stateChanged 372
#define QAudioInput_notify 373

#define QOpenGLWidget_aboutToCompose  374
#define QOpenGLWidget_frameSwapped  375
#define QOpenGLWidget_aboutToResize  376
#define QOpenGLWidget_resized  377
#define QOpenGLWidget_initializeGL  378
#define QOpenGLWidget_resizeGL  379
#define QOpenGLWidget_paintGL  380
