#include "qxlibrary_global.h"
#include "QXApplication.h"
#ifdef WIN32
#include <conio.h>
#endif


megInfo megs[] = {
	{ "Timer",1 },
	{ "MouseButtonPress",2 },
	{ "MouseButtonRelease",3 },
	{ "MouseButtonDblClick",4 },
	{ "MouseMove",5 },
	{ "KeyPress",6 },
	{ "KeyRelease",7 },
	{ "FocusIn",8 },
	{ "FocusOut",9 },
	{ "FocusAboutToChange",23 },
	{ "Enter",10 },
	{ "Leave",11 },
	{ "Paint",12 },
	{ "Move",13 },
	{ "Resize",14 },
	{ "Create",15 },
	{ "Destroy",16 },
	{ "Show",17 },
	{ "Hide",18 },
	{ "Close",19 },
	{ "Quit",20 },
	{ "ParentChange",21 },
	{ "ParentAboutToChange",131 },
	{ "ThreadChange",22 },
	{ "WindowActivate",24 },
	{ "WindowDeactivate",25 },
	{ "ShowToParent",26 },
	{ "HideToParent",27 },
	{ "Wheel",31 },
	{ "WindowTitleChange",33 },
	{ "WindowIconChange",34 },
	{ "ApplicationWindowIconChange",35 },
	{ "ApplicationFontChange",36 },
	{ "ApplicationLayoutDirectionChange",37 },
	{ "ApplicationPaletteChange",38 },
	{ "PaletteChange",39 },
	{ "Clipboard",40 },
	{ "Speech",42 },
	{ "MetaCall",43 },
	{ "SockAct",50 },
	{ "WinEventAct",132 },
	{ "DeferredDelete",52 },
	{ "DragEnter",60 },
	{ "DragMove",61 },
	{ "DragLeave",62 },
	{ "Drop",63 },
	{ "DragResponse",64 },
	{ "ChildAdded",68 },
	{ "ChildPolished",69 },
	{ "ChildRemoved",71 },
	{ "ShowWindowRequest",73 },
	{ "PolishRequest",74 },
	{ "Polish",75 },
	{ "LayoutRequest",76 },
	{ "UpdateRequest",77 },
	{ "UpdateLater",78 },
	{ "EmbeddingControl",79 },
	{ "ActivateControl",80 },
	{ "DeactivateControl",81 },
	{ "ContextMenu",82 },
	{ "InputMethod",83 },
	{ "TabletMove",87 },
	{ "LocaleChange",88 },
	{ "LanguageChange",89 },
	{ "LayoutDirectionChange",90 },
	{ "Style",91 },
	{ "TabletPress",92 },
	{ "TabletRelease",93 },
	{ "OkRequest",94 },
	{ "HelpRequest",95 },
	{ "IconDrag",96 },
	{ "FontChange",97 },
	{ "EnabledChange",98 },
	{ "ActivationChange",99 },
	{ "StyleChange",100 },
	{ "IconTextChange",101 },
	{ "ModifiedChange",102 },
	{ "MouseTrackingChange",109 },
	{ "WindowBlocked",103 },
	{ "WindowUnblocked",104 },
	{ "WindowStateChange",105 },
	{ "ReadOnlyChange",106 },
	{ "ToolTip",110 },
	{ "WhatsThis",111 },
	{ "StatusTip",112 },
	{ "ActionChanged",113 },
	{ "ActionAdded",114 },
	{ "ActionRemoved",115 },
	{ "FileOpen",116 },
	{ "Shortcut",117 },
	{ "ShortcutOverride",51 },
	{ "WhatsThisClicked",118 },
	{ "ToolBarChange",120 },
	{ "ApplicationActivate",121 },
	{ "ApplicationDeactivate",122 },
	{ "QueryWhatsThis",123 },
	{ "EnterWhatsThisMode",124 },
	{ "LeaveWhatsThisMode",125 },
	{ "ZOrderChange",126 },
	{ "HoverEnter",127 },
	{ "HoverLeave",128 },
	{ "HoverMove",129 },
	{ "EnterEditFocus",150 },
	{ "LeaveEditFocus",151 },
	{ "AcceptDropsChange",152 },
	{ "ZeroTimerEvent",154 },
	{ "GraphicsSceneMouseMove",155 },
	{ "GraphicsSceneMousePress",156 },
	{ "GraphicsSceneMouseRelease",157 },
	{ "GraphicsSceneMouseDoubleClick",158 },
	{ "GraphicsSceneContextMenu",159 },
	{ "GraphicsSceneHoverEnter",160 },
	{ "GraphicsSceneHoverMove",161 },
	{ "GraphicsSceneHoverLeave",162 },
	{ "GraphicsSceneHelp",163 },
	{ "GraphicsSceneDragEnter",164 },
	{ "GraphicsSceneDragMove",165 },
	{ "GraphicsSceneDragLeave",166 },
	{ "GraphicsSceneDrop",167 },
	{ "GraphicsSceneWheel",168 },
	{ "KeyboardLayoutChange",169 },
	{ "DynamicPropertyChange",170 },
	{ "TabletEnterProximity",171 },
	{ "TabletLeaveProximity",172 },
	{ "NonClientAreaMouseMove",173 },
	{ "NonClientAreaMouseButtonPress",174 },
	{ "NonClientAreaMouseButtonRelease",175 },
	{ "NonClientAreaMouseButtonDblClick",176 },
	{ "MacSizeChange",177 },
	{ "ContentsRectChange",178 },
	{ "MacGLWindowChange",179 },
	{ "FutureCallOut",180 },
	{ "GraphicsSceneResize",181 },
	{ "GraphicsSceneMove",182 },
	{ "CursorChange",183 },
	{ "ToolTipChange",184 },
	{ "NetworkReplyUpdated",185 },
	{ "GrabMouse",186 },
	{ "UngrabMouse",187 },
	{ "GrabKeyboard",188 },
	{ "UngrabKeyboard",189 },
	{ "MacGLClearDrawable",191 },
	{ "StateMachineSignal",192 },
	{ "StateMachineWrapped",193 },
	{ "TouchBegin",194 },
	{ "TouchUpdate",195 },
	{ "TouchEnd",196 },
	{ "NativeGesture",197 },
	{ "RequestSoftwareInputPanel",199 },
	{ "CloseSoftwareInputPanel",200 },
	{ "WinIdChange",203 },
	{ "Gesture",198 },
	{ "GestureOverride",202 },
	{ "ScrollPrepare",204 },
	{ "Scroll",205 },
	{ "Expose",206 },
	{ "InputMethodQuery",207 },
	{ "OrientationChange",208 },
	{ "TouchCancel",209 },
	{ "ThemeChange",210 },
	{ "SockClose",211 },
	{ "PlatformPanel",212 },
	{ "StyleAnimationUpdate",213 },
	{ "ApplicationStateChange",214 },
	{ "WindowChangeInternal",215 },
	{ "ScreenChangeInternal",216 },
	{ "PlatformSurface",217 },
	{ "Pointer",218 },
	{ "TabletTrackingChange",219 },
	{ "Trigger",TRIGGER_ID },
	{ "onItemPressed",ITEMPRESS_ID },
	{ "onItemClicked",ITEMCLK_ID },
	{ "onItemDoubleClicked",ITEMDBCLK_ID },
	{ "ItemActived",ITEMACTIVE_ID },
	{ "ItemEntered",ITEMENTER_ID },
	{ "ItemChanged",ITEMCHANGE_ID },
	{ "ItemExpanded",ITEMEXPAND_ID },
	{ "ItemCollapsed",ITEMCOLLPA_ID },
	{ "CurrentItemChanged",ITEMCURCHA_ID },
	{ "ItemSelectionChanged",ITEMSELCHA_ID },
	{ "onNotify",NOTIFY_ID },
	{ "nativeFinalize",FINALIZE_ID },
	{ "onClick",BTNCLICK_ID },
	{ "onToggle",TOGGLE_ID },
	{ "onPress",ONPRESS_ID },
	{ "onRelease",ONRELEASE_ID },
	{ "onFinish",ONFINISH_ID },
	{ "onAccept",ONACCEPT_ID },
	{ "onReject",ONREJECT_ID },
	{ "SCEN_CHANGE",241 },
	{ "ON_CALLTIPCLICK",242 },
	{ "ON_CHARADDED",243 },
	{ "ON_DOUBLECLICK",244 },
	{ "ON_DWELLEND",245 },
	{ "ON_DWELLSTART",246 },
	{ "ON_FOCUSIN",247 },
	{ "ON_FOCUSOUT",248 },
	{ "ON_HOTSPOTCLICK",249 },
	{ "ON_HOTSPOTDOUBLECLICK",250 },
	{ "ON_HOTSPOTRELEASECLICK",251 },
	{ "ON_INDICATORCLICK",252 },
	{ "ON_INDICATORRELEASE",253 },
	{ "ON_MACRORECORD",254 },
	{ "ON_MARGINCLICK",255 },
	{ "ON_MARGINRIGHTCLICK",256 },
	{ "ON_MODIFIED",257 },
	{ "ON_MODIFYATTEMPTRO",258 },
	{ "ON_NEEDSHOWN",259 },
	{ "ON_PAINTED",260 },
	{ "ON_SAVEPOINTLEFT",261 },
	{ "ON_SAVEPOINTREACHED",262 },
	{ "ON_STYLENEEDED",263 },
	{ "ON_UPDATEUI",264 },
	{ "ON_USERLISTSELECTION",265 },
	{ "ON_USERLISTSELECTION1",266 },
	{ "ON_ZOOM",267 },
	{ "ON_SELCHANGED" , 268 },
	{ "ON_AUTOCCANCELLED" , 269 },
	{ "ON_AUTOCCHARDELETED" , 270 },
	{ "ON_AUTOCCOMPLETED" , 271 },
	{ "ON_AUTOCSELECTION" , 272 },
	{ "ON_AUTOCSELECTION" , 273 },
	{ "ON_EDITCHANGE" , 274 },
	{ "ON_EDITEDITED" , 275 },
	{ "ON_EDITPOSCHANGE" , 276 },
	{ "ON_EDITRETURN" , 277 },
	{ "ON_EDITFINISH" , 278 },
	{ "ON_EDITSELCHANGE" , 279 },
	{ "ON_CURTEXTCHANGE" , 280 },
	{ "ON_ACTIVATED" , 281 },
	{ "ON_SELCHANGE" , 282 },
	{ "ON_FILECHANGE" , 283 },
	{ "ON_DIRCHANGE" , 284 },
	{ "ON_CELLCHANGE" , 285 },
	{ "ON_CELLITEMCHANGE", 286 },
	{ "ON_CELLPRESS", 287 },
	{ "ON_CELLITEMPRESS", 288 },
	{ "ON_CELLCLICK", 289 },
	{ "ON_CELLITEMCLICK", 290 },
	{ "ON_CELLDBCLICK", 291 },
	{ "ON_CELLITEMDBCLICK", 292 },
	{ "ON_CELLENTER", 293 },
	{ "ON_CELLITEMENTER", 294 },
	{ "ON_CELLACTIVE", 295 },
	{ "ON_CELLITEMACTIVE", 296 },
	{ "ON_ENUMCHANGED", 297 },
	{ "ON_VVALUECHANGE", 298 },
	{ "ON_VATTRCHANGE", 299 },
	{ "ON_PRINTPREVIEWREQ", 300 },
	{ "ON_REPORTRENDERSTARTED", 301 },
	{ "ON_REPORTRENDERPAGEFINISH", 302 },
	{ "ON_REPORTRENDERFINISH", 303 },
	{ "ON_DATASOURCEGETCALLBACKDATA", 304 },
	{ "ON_DATASOURCECHANGEPOS", 305 },

	{ "ON_DATETIMECHANGE", 306 },
	{ "ON_DATECHANGE", 307 },
	{ "ON_TIMECHANGE", 308 },

	{ "ON_TEXTEDITCHANGE", 309 },
	{ "ON_TEXTEDITPOSCHANGE", 310 },
	{ "ON_TEXTEDITSELCHANGE", 311 },


	{ "ON_SLIDER_VALUECHANGED",	312 },
	{ "ON_SLIDER_SLIDERPRESSED",	313 },
	{ "ON_SLIDER_SLIDERMOVED",	314 },
	{ "ON_SLIDER_SLIDERRELEASED",	315 },
	{ "ON_SLIDER_RANGECHANGED",	316 },
	{ "ON_SLIDER_ACTIONTRIGGERED",	317 },


	{ "ON_QTABWIDGET_CURRENTCHANGED", 318 },
	{ "ON_QTABWIDGET_TABCLOSEREQUESTED", 319 },
	{ "ON_QTABWIDGET_TABBARCLICKED", 320 },
	{ "ON_QTABWIDGET_TABBARDOUBLECLICKED",	321 },

	{ "ON_QTABBAR_CURRENTCHANGED",	322 },
	{ "ON_QTABBAR_TABCLOSEREQUESTED",	323 },
	{ "ON_QTABBAR_TABMOVED",	324 },
	{ "ON_QTABBAR_TABBARCLICKED",	325 },
	{ "ON_QTABBAR_TABBARDOUBLECLICKED",	326 },

	{ "ON_QCW_SELECTIONCHANGED",	327 },
	{ "ON_QCW_CLICKED",	328 },
	{ "ON_QCW_ACTIVATED",	329 },
	{ "ON_QCW_CURRENTPAGECHANGED",	330 },

	{ "ON_QSTI_ACTIVATED",	331 },
	{ "ON_QSTI_CLICKED",	332 },

	{ "ON_QH_SECTIONMOVED", 333 },
	{ "ON_QH_SECTIONRESIZED", 334 },
	{ "ON_QH_SECTIONPRESSED", 335},
	{ "ON_QH_SECTIONCLICKED", 336 },
	{ "ON_QH_SECTIONENTERED", 337 },
	{ "ON_QH_SECTIONDOUBLECLICKED", 338 },
	{ "ON_QH_SECTIONCOUNTCHANGED", 339 },
	{ "ON_QH_SECTIONHANDLEDOUBLECLICKED", 340 },
	{ "ON_QH_GEOMETRIESCHANGED", 341 },
	{ "ON_QH_SORTINDICATORCHANGED", 342 },
	{ "ON_QWT_BACKREQUESTED", 343 },
	{ "ON_QWT_SHOWHELP", 344 },

	{ "ON_QMediaPlayer_mediaChanged", 345 },
	{ "ON_QMediaPlayer_currentMediaChanged", 346 },
	{ "ON_QMediaPlayer_stateChanged", 347 },
	{ "ON_QMediaPlayer_mediaStatusChanged", 348 },
	{ "ON_QMediaPlayer_durationChanged", 349 },
	{ "ON_QMediaPlayer_positionChanged", 350 },
	{ "ON_QMediaPlayer_volumeChanged", 351 },
	{ "ON_QMediaPlayer_mutedChanged", 352 },
	{ "ON_QMediaPlayer_audioAvailableChanged", 353 },
	{ "ON_QMediaPlayer_videoAvailableChanged", 354 },
	{ "ON_QMediaPlayer_bufferStatusChanged", 355 },
	{ "ON_QMediaPlayer_seekableChanged", 356 },
	{ "ON_QMediaPlayer_playbackRateChanged", 357 },
	{ "ON_QMediaPlayer_audioRoleChanged", 358 },
	{ "ON_QMediaPlayer_error", 359 },

	{ "ON_QMediaObject_notifyIntervalChanged", 360 },
	{ "ON_QMediaObject_metaDataAvailableChanged", 361 },
	{ "ON_QMediaObject_metaDataChanged", 362 },
	{ "ON_QMediaObject_availabilityChanged", 363 },
	{ "ON_QMediaObject_availabilityChanged", 364 },

	{ "QVideoWidget_fullScreenChanged", 365 },
	{ "QVideoWidget_brightnessChanged", 366 },
	{ "QVideoWidget_contrastChanged", 367 },
	{ "QVideoWidget_hueChanged", 368 },
	{ "QVideoWidget_saturationChanged", 369 },

	{ "QAudioOutput_stateChanged", 370 },
	{ "QAudioOutput_notify", 371 },

	{ "QAudioInput_stateChanged", 372 },
	{ "QAudioInput_notify", 373 },

	{ "QOpenGLWidget_aboutToCompose", 374 },
	{ "QOpenGLWidget_frameSwapped", 375 },
	{ "QOpenGLWidget_aboutToResize", 376 },
	{ "QOpenGLWidget_resized", 377 },
	{ "QOpenGLWidget_initializeGL", 378 },
	{ "QOpenGLWidget_resizeGL", 379 },
	{ "QOpenGLWidget_paintGL", 380 },

};


size_t getEventMaxCount() {
	size_t max_c = 0;
	for (size_t i = 0; i < _countof(megs); i++) {
		if (megs[i].id >= max_c) {
			max_c = megs[i].id + 1;
		}
	}
	return max_c;
}

size_t getEventSize() {
	return _countof(megs);
}
XIDENT  methods [] = 
{
	{ "/void@/Qt/QObject/onTimer(/int)",0 },
	{ "/void@/Qt/QObject/onMouseButtonPress(/int,/int,/int,/int,/int)",0 },
	{ "/void@/Qt/QObject/onMouseButtonRelease(/int,/int,/int,/int,/int)",0 },
	{ "/void@/Qt/QObject/onMouseButtonDblClick(/int,/int,/int,/int,/int)",0 },
	{ "/void@/Qt/QObject/onMouseMove(/int,/int,/int,/int,/int)",0 },
	{ "/bool@/Qt/QObject/onKeyPress(/int,/bool,/int,/String,/int,/int,/int)",0 },
	{ "/bool@/Qt/QObject/onKeyRelease(/int,/bool,/int,/String,/int,/int,/int)",0 },
	{ "/void@/Qt/QObject/onFocusIn(/bool,/int)",0 },
	{ "/void@/Qt/QObject/onFocusOut(/bool,/int)",0 },
	{ "/void@/Qt/QObject/onFocusAboutToChange(/bool,/int)",0 },
	{ "/void@/Qt/QObject/onEnter(/int,/int)",0 },
	{ "/void@/Qt/QObject/onLeave()",0 },
	{ "/void@/Qt/QObject/onPaint(/int,/int,/int,/int,/long)",0 },
	{ "/void@/Qt/QObject/onMove(/int,/int,/int,/int)",0 },
	{ "/void@/Qt/QObject/onResize(/int,/int,/int,/int)",0 },
	{ "/void@/Qt/QObject/onCreate()",0 },
	{ "/void@/Qt/QObject/onDestroy()",0 },
	{ "/void@/Qt/QObject/onShow()",0 },
	{ "/void@/Qt/QObject/onHide()",0 },
	{ "/bool@/Qt/QObject/onClose()",0 },
	{ "/void@/Qt/QObject/onQuit()",0 },
	{ "/void@/Qt/QObject/onParentChange()",0 },
	{ "/void@/Qt/QObject/onParentAboutToChange()",0 },
	{ "/void@/Qt/QObject/onThreadChange()",0 },
	{ "/void@/Qt/QObject/onWindowActivate()",0 },
	{ "/void@/Qt/QObject/onWindowDeactivate()",0 },
	{ "/void@/Qt/QObject/onShowToParent()",0 },
	{ "/void@/Qt/QObject/onHideToParent()",0 },
	{ "/void@/Qt/QObject/onWheel(/int,/int,/int,/int,/int,/bool)",0 },
	{ 0, 0 },
	{ 0, 0 },
	{ 0, 0 },
	{ 0, 0 },
	{ 0, 0 },
	{ 0, 0 },
	{ 0, 0 },
	{ "/void@/Qt/QObject/onClipboard()",0 },
	{ 0, 0 },
	{ 0, 0 },
	{ 0, 0 },
	{ "/void@/Qt/QObject/onWinEventAct()",0 },
	{ "/void@/Qt/QObject/onDeferredDelete()",0 },
	{ "/bool@/Qt/QObject/onDragEnter(/int,/int,/int,/int)",0 },
	{ "/bool@/Qt/QObject/onDragMove(/int,/int,/int,/int)",0 },
	{ "/bool@/Qt/QObject/onDragLeave(/int,/int,/int,/int)",0 },
	{ "/void@/Qt/QObject/onDrop(/*[])",0 },
	{ "/void@/Qt/QObject/onDragResponse()",0 },
	{ 0, 0 },
	{ 0, 0 },
	{ 0, 0 },
	{ 0, 0 },
	{ 0, 0 },
	{ 0, 0 },
	{ "/void@/Qt/QObject/onLayoutRequest()",0 },
	{ "/void@/Qt/QObject/onUpdateRequest()",0 },
	{ "/void@/Qt/QObject/onUpdateLater()",0 },
	{ "/void@/Qt/QObject/onEmbeddingControl()",0 },
	{ "/void@/Qt/QObject/onActivateControl()",0 },
	{ "/void@/Qt/QObject/onDeactivateControl()",0 },
	{ "/void@/Qt/QObject/onContextMenu(/int,/int,/int)",0 },
	{ "/void@/Qt/QObject/onInputMethod()",0 },
	{ "/void@/Qt/QObject/onTabletMove()",0 },
	{ "/void@/Qt/QObject/onLocaleChange()",0 },
	{ "/void@/Qt/QObject/onLanguageChange()",0 },
	{ "/void@/Qt/QObject/onLayoutDirectionChange()",0 },
	{ "/void@/Qt/QObject/onStyle()",0 },
	{ "/void@/Qt/QObject/onTabletPress()",0 },
	{ "/void@/Qt/QObject/onTabletRelease()",0 },
	{ "/void@/Qt/QObject/onOkRequest()",0 },
	{ "/void@/Qt/QObject/onHelpRequest(/int,/int)",0 },
	{ "/void@/Qt/QObject/onIconDrag()",0 },
	{ "/void@/Qt/QObject/onFontChange()",0 },
	{ "/void@/Qt/QObject/onEnabledChange()",0 },
	{ "/void@/Qt/QObject/onActivationChange()",0 },
	{ "/void@/Qt/QObject/onStyleChange()",0 },
	{ "/void@/Qt/QObject/onIconTextChange()",0 },
	{ "/void@/Qt/QObject/onModifiedChange()",0 },
	{ "/void@/Qt/QObject/onMouseTrackingChange()",0 },
	{ "/void@/Qt/QObject/onWindowBlocked()",0 },
	{ "/void@/Qt/QObject/onWindowUnblocked()",0 },
	{ "/void@/Qt/QObject/onWindowStateChange(/int,/int)",0 },
	{ "/void@/Qt/QObject/onReadOnlyChange()",0 },
	{ "/void@/Qt/QObject/onToolTip(/int,/int)",0 },
	{ "/void@/Qt/QObject/onWhatsThis(/int,/int)",0 },
	{ "/void@/Qt/QObject/onStatusTip(/String)",0 },
	{ "/void@/Qt/QObject/onActionChanged()",0 },
	{ "/void@/Qt/QObject/onActionAdded()",0 },
	{ "/void@/Qt/QObject/onActionRemoved()",0 },
	{ "/void@/Qt/QObject/onFileOpen()",0 },
	{ "/void@/Qt/QObject/onShortcut(/int,/int,/bool)",0 },
	{ "/void@/Qt/QObject/onShortcutOverride()",0 },
	{ "/void@/Qt/QObject/onWhatsThisClicked()",0 },
	{ "/void@/Qt/QObject/onToolBarChange()",0 },
	{ "/void@/Qt/QObject/onApplicationActivate()",0 },
	{ "/void@/Qt/QObject/onApplicationDeactivate()",0 },
	{ "/void@/Qt/QObject/onQueryWhatsThis()",0 },
	{ "/void@/Qt/QObject/onEnterWhatsThisMode()",0 },
	{ "/void@/Qt/QObject/onLeaveWhatsThisMode()",0 },
	{ "/void@/Qt/QObject/onZOrderChange()",0 },
	{ "/void@/Qt/QObject/onHoverEnter(/int,/int)",0 },
	{ "/void@/Qt/QObject/onHoverLeave(/int,/int)",0 },
	{ "/void@/Qt/QObject/onHoverMove(/int,/int)",0 },
	{ 0,0 },
	{ 0,0 },
	{ "/void@/Qt/QObject/onAcceptDropsChange()",0 },
	{ "/void@/Qt/QObject/onZeroTimerEvent()",0 },
	{ "/void@/Qt/QObject/onGraphicsSceneMouseMove()",0 },
	{ "/void@/Qt/QObject/onGraphicsSceneMousePress()",0 },
	{ "/void@/Qt/QObject/onGraphicsSceneMouseRelease()",0 },
	{ "/void@/Qt/QObject/onGraphicsSceneMouseDoubleClick()",0 },
	{ "/void@/Qt/QObject/onGraphicsSceneContextMenu()",0 },
	{ "/void@/Qt/QObject/onGraphicsSceneHoverEnter()",0 },
	{ "/void@/Qt/QObject/onGraphicsSceneHoverMove()",0 },
	{ "/void@/Qt/QObject/onGraphicsSceneHoverLeave()",0 },
	{ "/void@/Qt/QObject/onGraphicsSceneHelp()",0 },
	{ "/void@/Qt/QObject/onGraphicsSceneDragEnter()",0 },
	{ "/void@/Qt/QObject/onGraphicsSceneDragMove()",0 },
	{ "/void@/Qt/QObject/onGraphicsSceneDragLeave()",0 },
	{ "/void@/Qt/QObject/onGraphicsSceneDrop()",0 },
	{ "/void@/Qt/QObject/onGraphicsSceneWheel()",0 },
	{ "/void@/Qt/QObject/onKeyboardLayoutChange()",0 },
	{ "/void@/Qt/QObject/onDynamicPropertyChange()",0 },
	{ "/void@/Qt/QObject/onTabletEnterProximity()",0 },
	{ "/void@/Qt/QObject/onTabletLeaveProximity()",0 },
	{ "/void@/Qt/QObject/onNonClientAreaMouseMove()",0 },
	{ "/void@/Qt/QObject/onNonClientAreaMouseButtonPress()",0 },
	{ "/void@/Qt/QObject/onNonClientAreaMouseButtonRelease()",0 },
	{ "/void@/Qt/QObject/onNonClientAreaMouseButtonDblClick()",0 },
	{ "/void@/Qt/QObject/onMacSizeChange()",0 },
	{ "/void@/Qt/QObject/onContentsRectChange()",0 },
	{ "/void@/Qt/QObject/onMacGLWindowChange()",0 },
	{ "/void@/Qt/QObject/onFutureCallOut()",0 },
	{ "/void@/Qt/QObject/onGraphicsSceneResize()",0 },
	{ "/void@/Qt/QObject/onGraphicsSceneMove()",0 },
	{ "/void@/Qt/QObject/onCursorChange()",0 },
	{ "/void@/Qt/QObject/onToolTipChange()",0 },
	{ "/void@/Qt/QObject/onNetworkReplyUpdated()",0 },
	{ "/void@/Qt/QObject/onGrabMouse()",0 },
	{ "/void@/Qt/QObject/onUngrabMouse()",0 },
	{ "/void@/Qt/QObject/onGrabKeyboard()",0 },
	{ "/void@/Qt/QObject/onUngrabKeyboard()",0 },
	{ "/void@/Qt/QObject/onMacGLClearDrawable()",0 },
	{ "/void@/Qt/QObject/onStateMachineSignal()",0 },
	{ "/void@/Qt/QObject/onStateMachineWrapped()",0 },
	{ "/void@/Qt/QObject/onTouchBegin()",0 },
	{ "/void@/Qt/QObject/onTouchUpdate()",0 },
	{ "/void@/Qt/QObject/onTouchEnd()",0 },
	{ "/void@/Qt/QObject/onNativeGesture()",0 },
	{ "/void@/Qt/QObject/onRequestSoftwareInputPanel()",0 },
	{ "/void@/Qt/QObject/onCloseSoftwareInputPanel()",0 },
	{ "/void@/Qt/QObject/onWinIdChange()",0 },
	{ "/void@/Qt/QObject/onGesture()",0 },
	{ "/void@/Qt/QObject/onGestureOverride()",0 },
	{ "/void@/Qt/QObject/onScrollPrepare()",0 },
	{ "/void@/Qt/QObject/onScroll()",0 },
	{ "/void@/Qt/QObject/onExpose()",0 },
	{ "/void@/Qt/QObject/onInputMethodQuery()",0 },
	{ "/void@/Qt/QObject/onOrientationChange()",0 },
	{ "/void@/Qt/QObject/onTouchCancel()",0 },
	{ "/void@/Qt/QObject/onThemeChange()",0 },
	{ "/void@/Qt/QObject/onSockClose()",0 },
	{ "/void@/Qt/QObject/onPlatformPanel()",0 },
	{ "/void@/Qt/QObject/onStyleAnimationUpdate()",0 },
	{ "/void@/Qt/QObject/onApplicationStateChange()",0 },
	{ "/void@/Qt/QObject/onWindowChangeInternal()",0 },
	{ "/void@/Qt/QObject/onScreenChangeInternal()",0 },
	{ "/void@/Qt/QObject/onPlatformSurface()",0 },
	{ "/void@/Qt/QObject/onPointer()",0 },
	{ "/void@/Qt/QObject/onTabletTrackingChange()",0 },
	{ "/void@/Qt/QObject/onTrigger()",0 },
	{ "/void@/Qt/QObject/onItemPressed(/long,/int)",0 },
	{ "/void@/Qt/QObject/onItemClicked(/long,/int)",0 },
	{ "/void@/Qt/QObject/onItemDoubleClicked(/long,/int)",0 },
	{ "/void@/Qt/QObject/onItemActived(/long,/int)",0 },
	{ "/void@/Qt/QObject/onItemEntered(/long,/int)",0 },
	{ "/void@/Qt/QObject/onItemChanged(/long,/int)",0 },
	{ "/void@/Qt/QObject/onItemExpanded(/long)",0 },
	{ "/void@/Qt/QObject/onItemCollapsed(/long)",0 },
	{ "/void@/Qt/QObject/onCurrentItemChanged(/long,/long)",0 },
	{ "/void@/Qt/QObject/onItemSelectionChanged()",0 },
	{ "/void@/Qt/QObject/onNotify(/long)",0 },
	{ "/void@/Qt/QObject/nativeFinalize()",0 },
	{ "/void@/Qt/QObject/onClick(/bool)",0 },
	{ "/void@/Qt/QObject/onToggle(/bool)",0 },
	{ "/void@/Qt/QObject/onPress()",0 },
	{ "/void@/Qt/QObject/onRelease()",0 },
	{ "/void@/Qt/QObject/onFinish(/int)",0 },
	{ "/void@/Qt/QObject/onAccept()",0 },
	{ "/void@/Qt/QObject/onReject()",0 },
	{ "/void@/Qt/QObject/SCEN_CHANGE()" , 0 },
	{ "/void@/Qt/QObject/ON_CALLTIPCLICK(/int)" , 0 },
	{ "/void@/Qt/QObject/ON_CHARADDED(/int)" , 0 },
	{ "/void@/Qt/QObject/ON_DOUBLECLICK(/int,/int,/int)" , 0 },
	{ "/void@/Qt/QObject/ON_DWELLEND(/int,/int,/int)" , 0 },
	{ "/void@/Qt/QObject/ON_DWELLSTART(/int,/int,/int)" , 0 },
	{ "/void@/Qt/QObject/ON_FOCUSIN()" , 0 },
	{ "/void@/Qt/QObject/ON_FOCUSOUT()" , 0 },
	{ "/void@/Qt/QObject/ON_HOTSPOTCLICK(/int,/int)" , 0 },
	{ "/void@/Qt/QObject/ON_HOTSPOTDOUBLECLICK(/int,/int)" , 0 },
	{ "/void@/Qt/QObject/ON_HOTSPOTRELEASECLICK(/int,/int)" , 0 },
	{ "/void@/Qt/QObject/ON_INDICATORCLICK(/int,/int)" , 0 },
	{ "/void@/Qt/QObject/ON_INDICATORRELEASE(/int,/int)" , 0 },
	{ "/void@/Qt/QObject/ON_MACRORECORD(/int,/long,/long)" , 0 },
	{ "/void@/Qt/QObject/ON_MARGINCLICK(/int,/int,/int)" , 0 },
	{ "/void@/Qt/QObject/ON_MARGINRIGHTCLICK(/int,/int,/int)" , 0 },
	{ "/void@/Qt/QObject/ON_MODIFIED(/int,/int,/String,/int,/int,/int,/int,/int,/int,/int)" , 0 },
	{ "/void@/Qt/QObject/ON_MODIFYATTEMPTRO()" , 0 },
	{ "/void@/Qt/QObject/ON_NEEDSHOWN(/int,/int)" , 0 },
	{ "/void@/Qt/QObject/ON_PAINTED()" , 0 },
	{ "/void@/Qt/QObject/ON_SAVEPOINTLEFT()" , 0 },
	{ "/void@/Qt/QObject/ON_SAVEPOINTREACHED()" , 0 },
	{ "/void@/Qt/QObject/ON_STYLENEEDED(/int)" , 0 },
	{ "/void@/Qt/QObject/ON_UPDATEUI(/int)" , 0 },
	{ "/void@/Qt/QObject/ON_USERLISTSELECTION(/String,/int,/int,/int)" , 0 },
	{ "/void@/Qt/QObject/ON_USERLISTSELECTION(/String,/int)" , 0 },
	{ "/void@/Qt/QObject/ON_ZOOM()" , 0 },
	{ "/void@/Qt/QObject/QON_SELCHANGED(/bool)" , 0 },
	{ "/void@/Qt/QObject/ON_AUTOCCANCELLED()" , 0 },
	{ "/void@/Qt/QObject/ON_AUTOCCHARDELETED()" , 0 },
	{ "/void@/Qt/QObject/ON_AUTOCCOMPLETED(/String,/int,/int,/int)" , 0 },
	{ "/void@/Qt/QObject/ON_AUTOCSELECTION(/String,/int,/int,/int)" , 0 },
	{ "/void@/Qt/QObject/ON_AUTOCSELECTION(/String,/int)" , 0 },
	{ "/void@/Qt/QObject/onTextChanged(/String)" , 0 },
	{ "/void@/Qt/QObject/onTextEdited(/String)" , 0 },
	{ "/void@/Qt/QObject/onCursorPositionChanged(/int,/int)" , 0 },
	{ "/void@/Qt/QObject/onReturnPressed()" , 0 },
	{ "/void@/Qt/QObject/onEditingFinished()" , 0 },
	{ "/void@/Qt/QObject/onSelectionChanged()" , 0 },
	{ "/void@/Qt/QObject/onCurrentTextChange(/String)" , 0 },
	{ "/void@/Qt/QObject/onActivated(/int)" , 0 },
	{ "/void@/Qt/QObject/onItemSelected(/int)" , 0 },
	{ "/void@/Qt/QObject/onFileChanged(/String)" , 0 },
	{ "/void@/Qt/QObject/onDirChange(/String)" , 0 },
	{ "/void@/Qt/QObject/onCellChange(/int,/int)" , 0 },
	{ "/void@/Qt/QObject/onItemChange(/long)" , 0 },
	{ "/void@/Qt/QObject/onCellPress(/int,/int)" , 0 },
	{ "/void@/Qt/QObject/onItemPress(/long)" , 0 },
	{ "/void@/Qt/QObject/onCellClick(/int,/int)" , 0 },
	{ "/void@/Qt/QObject/onItemClick(/long)" , 0 },
	{ "/void@/Qt/QObject/onCellDBClick(/int,/int)" , 0 },
	{ "/void@/Qt/QObject/onItemDBClick(/long)" , 0 },
	{ "/void@/Qt/QObject/onCellEnter(/int,/int)" , 0 },
	{ "/void@/Qt/QObject/onItemEnter(/long)" , 0 },
	{ "/void@/Qt/QObject/onCellActived(/int,/int)" , 0 },
	{ "/void@/Qt/QObject/onItemActived(/long)" , 0 },
	{ "/void@/Qt/QObject/onEnumPropertyValueChanged(/long,/int)" , 0 },
	{ "/void@/Qt/QObject/onVariantPropertyValueChanged(/long,/int,/String)" , 0 },
	{ "/void@/Qt/QObject/onVariantPropertyAttributeChanged(/long,/String,/int,/String)" , 0 },
	{ "/void@/Qt/QPrintPreviewDialog/onPreviewRequest(/long)" , 0 },
	{ "/void@/Qt/ReportEngine/renderStarted()" , 0 },
	{ "/void@/Qt/ReportEngine/renderPageFinished(/int)" , 0 },
	{ "/void@/Qt/ReportEngine/renderFinished()" , 0 },
	{ "/*@/Qt/ReportEngine/ICallbackDatasource/getCallbackData(/Qt/ReportEngine/DataType,/int,/String)" , 0 },
	{ "/bool@/Qt/ReportEngine/ICallbackDatasource/changePos(/Qt/ReportEngine/ChangePosType)" , 0 },
	{ "/void@/Qt/QDateTimeEdit/onDateTimeChange(/long)" , 0 },
	{ "/void@/Qt/QDateTimeEdit/onDateChange(/int,/int,/int)" , 0 },
	{ "/void@/Qt/QDateTimeEdit/onTimeChange(/int,/int,/int,/int)" , 0 },
	{ "/void@/Qt/QTextEdit/onTextChanged()" , 0 },
	{ "/void@/Qt/QTextEdit/onCursorPositionChanged()" , 0 },
	{ "/void@/Qt/QTextEdit/onSelectionChanged()" , 0 },
	{ "/void@/Qt/QAbstractSlider/onValueChanged(/int)",	0 },
	{ "/void@/Qt/QAbstractSlider/onPressed()",	0 },
	{ "/void@/Qt/QAbstractSlider/onMoved(/int)",	0 },
	{ "/void@/Qt/QAbstractSlider/onReleased()",	0 },
	{ "/void@/Qt/QAbstractSlider/onRangeChanged(/int,/int)",	0 },
	{ "/void@/Qt/QAbstractSlider/onActionTriggered(/int)",	0 },

	{ "/void@/Qt/QTabWidget/currentChanged(/int)",	0 },
	{ "/void@/Qt/QTabWidget/tabCloseRequested(/int)",	0 },
	{ "/void@/Qt/QTabWidget/tabBarClicked(/int)",	0 },
	{ "/void@/Qt/QTabWidget/tabBarDoubleClicked(/int)",	0 },

	{ "/void@/Qt/QTabBar/currentChanged(/int)",	0 },
	{ "/void@/Qt/QTabBar/tabCloseRequested(/int)",	0 },
	{ "/void@/Qt/QTabBar/tabMoved(/int,/int)",	0 },
	{ "/void@/Qt/QTabBar/tabBarClicked(/int)",	0 },
	{ "/void@/Qt/QTabBar/tabBarDoubleClicked(/int)",	0 },

	{ "/void@/Qt/QCalendarWidget/onSelectionChanged()",	0 },
	{ "/void@/Qt/QCalendarWidget/onClicked(/int,/int,/int)",	0 },
	{ "/void@/Qt/QCalendarWidget/onActivated(/int,/int,/int)",	0 },
	{ "/void@/Qt/QCalendarWidget/onCurrentPageChanged(/int,/int)",	0 },

	{ "/void@/Qt/QSystemTrayIcon/activated(/int)",	0 },
	{ "/void@/Qt/QSystemTrayIcon/messageClicked()",	0 },


	{ "/void@/Qt/QHeaderView/sectionMoved(/int,/int,/int)",	0 },
	{ "/void@/Qt/QHeaderView/sectionResized(/int,/int,/int)",	0 },
	{ "/void@/Qt/QHeaderView/sectionPressed(/int)",	0 },
	{ "/void@/Qt/QHeaderView/sectionClicked(/int)",	0 },
	{ "/void@/Qt/QHeaderView/sectionEntered(/int)",	0 },
	{ "/void@/Qt/QHeaderView/sectionDoubleClicked(/int)",	0 },
	{ "/void@/Qt/QHeaderView/sectionCountChanged(/int,/int)",	0 },
	{ "/void@/Qt/QHeaderView/sectionHandleDoubleClicked(/int)",	0 },
	{ "/void@/Qt/QHeaderView/geometriesChanged()",	0 },
	{ "/void@/Qt/QHeaderView/sortIndicatorChanged(/int,/int)",	0 },
	{ "/void@/Qtitan/WindowTitleBar/backRequested()",	0 },
	{ "/void@/Qtitan/WindowTitleBar/showHelp()", 0 },

	{ "/void@/Qt/QMediaPlayer/mediaChanged(/String)", 0 },
	{ "/void@/Qt/QMediaPlayer/currentMediaChanged(/String)", 0 },
	{ "/void@/Qt/QMediaPlayer/stateChanged(/Qt/QMediaPlayer/State)", 0 },
	{ "/void@/Qt/QMediaPlayer/mediaStatusChanged(/Qt/QMediaPlayer/MediaStatus)", 0 },
	{ "/void@/Qt/QMediaPlayer/durationChanged(/long)", 0 },
	{ "/void@/Qt/QMediaPlayer/positionChanged(/long)", 0 },
	{ "/void@/Qt/QMediaPlayer/volumeChanged(/int)", 0 },
	{ "/void@/Qt/QMediaPlayer/mutedChanged(/bool)", 0 },
	{ "/void@/Qt/QMediaPlayer/audioAvailableChanged(/bool)", 0 },
	{ "/void@/Qt/QMediaPlayer/videoAvailableChanged(/bool)", 0 },
	{ "/void@/Qt/QMediaPlayer/bufferStatusChanged(/int)", 0 },
	{ "/void@/Qt/QMediaPlayer/seekableChanged(/bool)", 0 },
	{ "/void@/Qt/QMediaPlayer/playbackRateChanged(/double)", 0 },
	{ "/void@/Qt/QMediaPlayer/audioRoleChanged(/Qt/QAudio/Role)", 0 },
	{ "/void@/Qt/QMediaPlayer/error(/Qt/QMediaPlayer/Error)", 0 },

	{ "/void@/Qt/QMediaObject/notifyIntervalChanged(/int)", 0 },
	{ "/void@/Qt/QMediaObject/metaDataAvailableChanged(/bool)", 0 },
	{ "/void@/Qt/QMediaObject/metaDataChanged()", 0 },
	{ "/void@/Qt/QMediaObject/availabilityChanged(/bool)", 0 },
	{ "/void@/Qt/QMediaObject/availabilityChanged(/Qt/AvailabilityStatus)", 0 },

	{ "/void@/Qt/QVideoWidget/fullScreenChanged(/bool)", 0 },
	{ "/void@/Qt/QVideoWidget/brightnessChanged(/int)", 0 },
	{ "/void@/Qt/QVideoWidget/contrastChanged(/int)", 0 },
	{ "/void@/Qt/QVideoWidget/hueChanged(/int)", 0 },
	{ "/void@/Qt/QVideoWidget/saturationChanged(/int)", 0 },
	{ "/void@/Qt/QAudioOutput/stateChanged(/Qt/QAudio/State)", 0 },
	{ "/void@/Qt/QAudioOutput/notify()", 0 },
	{ "/void@/Qt/QAudioInput/stateChanged(/Qt/QAudio/State)", 0 },
	{ "/void@/Qt/QAudioInput/notify()", 0 },

	{ "/void@/Qt/QOpenGLWidget/aboutToCompose()", 0 },
	{ "/void@/Qt/QOpenGLWidget/frameSwapped()", 0 },
	{ "/void@/Qt/QOpenGLWidget/aboutToResize()", 0 },
	{ "/void@/Qt/QOpenGLWidget/resized()", 0 },
	{ "/void@/Qt/QOpenGLWidget/initializeGL()", 0 },
	{ "/void@/Qt/QOpenGLWidget/resizeGL(/int,/int)", 0 },
	{ "/void@/Qt/QOpenGLWidget/paintGL()", 0 },
};
