#include "qxlibrary_global.h"
#include "QXApplication.h"
#ifdef WIN32
#include <conio.h>
#endif


megInfo megs[] = {
	{ "Timer",1 },
	{ "MouseButtonPress",2 },
	{ "MouseButtonRelease",3 },
	{ "MouseButtonDblClick",4 },
	{ "MouseMove",5 },
	{ "KeyPress",6 },
	{ "KeyRelease",7 },
	{ "FocusIn",8 },
	{ "FocusOut",9 },
	{ "FocusAboutToChange",23 },
	{ "Enter",10 },
	{ "Leave",11 },
	{ "Paint",12 },
	{ "Move",13 },
	{ "Resize",14 },
	{ "Create",15 },
	{ "Destroy",16 },
	{ "Show",17 },
	{ "Hide",18 },
	{ "Close",19 },
	{ "Quit",20 },
	{ "ParentChange",21 },
	{ "ParentAboutToChange",131 },
	{ "ThreadChange",22 },
	{ "WindowActivate",24 },
	{ "WindowDeactivate",25 },
	{ "ShowToParent",26 },
	{ "HideToParent",27 },
	{ "Wheel",31 },
	{ "WindowTitleChange",33 },
	{ "WindowIconChange",34 },
	{ "ApplicationWindowIconChange",35 },
	{ "ApplicationFontChange",36 },
	{ "ApplicationLayoutDirectionChange",37 },
	{ "ApplicationPaletteChange",38 },
	{ "PaletteChange",39 },
	{ "Clipboard",40 },
	{ "Speech",42 },
	{ "MetaCall",43 },
	{ "SockAct",50 },
	{ "WinEventAct",132 },
	{ "DeferredDelete",52 },
	{ "DragEnter",60 },
	{ "DragMove",61 },
	{ "DragLeave",62 },
	{ "Drop",63 },
	{ "DragResponse",64 },
	{ "ChildAdded",68 },
	{ "ChildPolished",69 },
	{ "ChildRemoved",71 },
	{ "ShowWindowRequest",73 },
	{ "PolishRequest",74 },
	{ "Polish",75 },
	{ "LayoutRequest",76 },
	{ "UpdateRequest",77 },
	{ "UpdateLater",78 },
	{ "EmbeddingControl",79 },
	{ "ActivateControl",80 },
	{ "DeactivateControl",81 },
	{ "ContextMenu",82 },
	{ "InputMethod",83 },
	{ "TabletMove",87 },
	{ "LocaleChange",88 },
	{ "LanguageChange",89 },
	{ "LayoutDirectionChange",90 },
	{ "Style",91 },
	{ "TabletPress",92 },
	{ "TabletRelease",93 },
	{ "OkRequest",94 },
	{ "HelpRequest",95 },
	{ "IconDrag",96 },
	{ "FontChange",97 },
	{ "EnabledChange",98 },
	{ "ActivationChange",99 },
	{ "StyleChange",100 },
	{ "IconTextChange",101 },
	{ "ModifiedChange",102 },
	{ "MouseTrackingChange",109 },
	{ "WindowBlocked",103 },
	{ "WindowUnblocked",104 },
	{ "WindowStateChange",105 },
	{ "ReadOnlyChange",106 },
	{ "ToolTip",110 },
	{ "WhatsThis",111 },
	{ "StatusTip",112 },
	{ "ActionChanged",113 },
	{ "ActionAdded",114 },
	{ "ActionRemoved",115 },
	{ "FileOpen",116 },
	{ "Shortcut",117 },
	{ "ShortcutOverride",51 },
	{ "WhatsThisClicked",118 },
	{ "ToolBarChange",120 },
	{ "ApplicationActivate",121 },
	{ "ApplicationDeactivate",122 },
	{ "QueryWhatsThis",123 },
	{ "EnterWhatsThisMode",124 },
	{ "LeaveWhatsThisMode",125 },
	{ "ZOrderChange",126 },
	{ "HoverEnter",127 },
	{ "HoverLeave",128 },
	{ "HoverMove",129 },
	{ "EnterEditFocus",150 },
	{ "LeaveEditFocus",151 },
	{ "AcceptDropsChange",152 },
	{ "ZeroTimerEvent",154 },
	{ "GraphicsSceneMouseMove",155 },
	{ "GraphicsSceneMousePress",156 },
	{ "GraphicsSceneMouseRelease",157 },
	{ "GraphicsSceneMouseDoubleClick",158 },
	{ "GraphicsSceneContextMenu",159 },
	{ "GraphicsSceneHoverEnter",160 },
	{ "GraphicsSceneHoverMove",161 },
	{ "GraphicsSceneHoverLeave",162 },
	{ "GraphicsSceneHelp",163 },
	{ "GraphicsSceneDragEnter",164 },
	{ "GraphicsSceneDragMove",165 },
	{ "GraphicsSceneDragLeave",166 },
	{ "GraphicsSceneDrop",167 },
	{ "GraphicsSceneWheel",168 },
	{ "KeyboardLayoutChange",169 },
	{ "DynamicPropertyChange",170 },
	{ "TabletEnterProximity",171 },
	{ "TabletLeaveProximity",172 },
	{ "NonClientAreaMouseMove",173 },
	{ "NonClientAreaMouseButtonPress",174 },
	{ "NonClientAreaMouseButtonRelease",175 },
	{ "NonClientAreaMouseButtonDblClick",176 },
	{ "MacSizeChange",177 },
	{ "ContentsRectChange",178 },
	{ "MacGLWindowChange",179 },
	{ "FutureCallOut",180 },
	{ "GraphicsSceneResize",181 },
	{ "GraphicsSceneMove",182 },
	{ "CursorChange",183 },
	{ "ToolTipChange",184 },
	{ "NetworkReplyUpdated",185 },
	{ "GrabMouse",186 },
	{ "UngrabMouse",187 },
	{ "GrabKeyboard",188 },
	{ "UngrabKeyboard",189 },
	{ "MacGLClearDrawable",191 },
	{ "StateMachineSignal",192 },
	{ "StateMachineWrapped",193 },
	{ "TouchBegin",194 },
	{ "TouchUpdate",195 },
	{ "TouchEnd",196 },
	{ "NativeGesture",197 },
	{ "RequestSoftwareInputPanel",199 },
	{ "CloseSoftwareInputPanel",200 },
	{ "WinIdChange",203 },
	{ "Gesture",198 },
	{ "GestureOverride",202 },
	{ "ScrollPrepare",204 },
	{ "Scroll",205 },
	{ "Expose",206 },
	{ "InputMethodQuery",207 },
	{ "OrientationChange",208 },
	{ "TouchCancel",209 },
	{ "ThemeChange",210 },
	{ "SockClose",211 },
	{ "PlatformPanel",212 },
	{ "StyleAnimationUpdate",213 },
	{ "ApplicationStateChange",214 },
	{ "WindowChangeInternal",215 },
	{ "ScreenChangeInternal",216 },
	{ "PlatformSurface",217 },
	{ "Pointer",218 },
	{ "TabletTrackingChange",219 },
	{ "Trigger",TRIGGER_ID },
	{ "onItemPressed",ITEMPRESS_ID },
	{ "onItemClicked",ITEMCLK_ID },
	{ "onItemDoubleClicked",ITEMDBCLK_ID },
	{ "ItemActived",ITEMACTIVE_ID },
	{ "ItemEntered",ITEMENTER_ID },
	{ "ItemChanged",ITEMCHANGE_ID },
	{ "ItemExpanded",ITEMEXPAND_ID },
	{ "ItemCollapsed",ITEMCOLLPA_ID },
	{ "CurrentItemChanged",ITEMCURCHA_ID },
	{ "ItemSelectionChanged",ITEMSELCHA_ID },
	{ "onNotify",NOTIFY_ID },
	{ "nativeFinalize",FINALIZE_ID },
	{ "onClick",BTNCLICK_ID },
	{ "onToggle",TOGGLE_ID },
	{ "onPress",ONPRESS_ID },
	{ "onRelease",ONRELEASE_ID },
	{ "onFinish",ONFINISH_ID },
	{ "onAccept",ONACCEPT_ID },
	{ "onReject",ONREJECT_ID },
	{ "SCEN_CHANGE",241 },
	{ "ON_CALLTIPCLICK",242 },
	{ "ON_CHARADDED",243 },
	{ "ON_DOUBLECLICK",244 },
	{ "ON_DWELLEND",245 },
	{ "ON_DWELLSTART",246 },
	{ "ON_FOCUSIN",247 },
	{ "ON_FOCUSOUT",248 },
	{ "ON_HOTSPOTCLICK",249 },
	{ "ON_HOTSPOTDOUBLECLICK",250 },
	{ "ON_HOTSPOTRELEASECLICK",251 },
	{ "ON_INDICATORCLICK",252 },
	{ "ON_INDICATORRELEASE",253 },
	{ "ON_MACRORECORD",254 },
	{ "ON_MARGINCLICK",255 },
	{ "ON_MARGINRIGHTCLICK",256 },
	{ "ON_MODIFIED",257 },
	{ "ON_MODIFYATTEMPTRO",258 },
	{ "ON_NEEDSHOWN",259 },
	{ "ON_PAINTED",260 },
	{ "ON_SAVEPOINTLEFT",261 },
	{ "ON_SAVEPOINTREACHED",262 },
	{ "ON_STYLENEEDED",263 },
	{ "ON_UPDATEUI",264 },
	{ "ON_USERLISTSELECTION",265 },
	{ "ON_USERLISTSELECTION1",266 },
	{ "ON_ZOOM",267 },
	{ "ON_SELCHANGED" , 268 },
	{ "ON_AUTOCCANCELLED" , 269 },
	{ "ON_AUTOCCHARDELETED" , 270 },
	{ "ON_AUTOCCOMPLETED" , 271 },
	{ "ON_AUTOCSELECTION" , 272 },
	{ "ON_AUTOCSELECTION" , 273 },
	{ "ON_EDITCHANGE" , 274 },
	{ "ON_EDITEDITED" , 275 },
	{ "ON_EDITPOSCHANGE" , 276 },
	{ "ON_EDITRETURN" , 277 },
	{ "ON_EDITFINISH" , 278 },
	{ "ON_EDITSELCHANGE" , 279 },
	{ "ON_CURTEXTCHANGE" , 280 },
	{ "ON_ACTIVATED" , 281 },
	{ "ON_SELCHANGE" , 282 },
	{ "ON_FILECHANGE" , 283 },
	{ "ON_DIRCHANGE" , 284 },
	{ "ON_CELLCHANGE" , 285 },
	{ "ON_CELLITEMCHANGE", 286 },
	{ "ON_CELLPRESS", 287 },
	{ "ON_CELLITEMPRESS", 288 },
	{ "ON_CELLCLICK", 289 },
	{ "ON_CELLITEMCLICK", 290 },
	{ "ON_CELLDBCLICK", 291 },
	{ "ON_CELLITEMDBCLICK", 292 },
	{ "ON_CELLENTER", 293 },
	{ "ON_CELLITEMENTER", 294 },
	{ "ON_CELLACTIVE", 295 },
	{ "ON_CELLITEMACTIVE", 296 },
	{ "ON_ENUMCHANGED", 297 },
	{ "ON_VVALUECHANGE", 298 },
	{ "ON_VATTRCHANGE", 299 },
	{ "ON_PRINTPREVIEWREQ", 300 },
};


size_t getEventMaxCount() {
	size_t max_c = 0;
	for (size_t i = 0; i < _countof(megs); i++) {
		if (megs[i].id >= max_c) {
			max_c = megs[i].id + 1;
		}
	}
	return max_c;
}

size_t getEventSize() {
	return _countof(megs);
}
XIDENT  methods [] = 
{
	{ "/void@/QXObject/onTimer(/int)",0 },
	{ "/void@/QXObject/onMouseButtonPress(/int,/int,/int,/int,/int)",0 },
	{ "/void@/QXObject/onMouseButtonRelease(/int,/int,/int,/int,/int)",0 },
	{ "/void@/QXObject/onMouseButtonDblClick(/int,/int,/int,/int,/int)",0 },
	{ "/void@/QXObject/onMouseMove(/int,/int,/int,/int,/int)",0 },
	{ "/bool@/QXObject/onKeyPress(/int,/bool,/int,/String,/int,/int,/int)",0 },
	{ "/bool@/QXObject/onKeyRelease(/int,/bool,/int,/String,/int,/int,/int)",0 },
	{ "/void@/QXObject/onFocusIn(/bool,/int)",0 },
	{ "/void@/QXObject/onFocusOut(/bool,/int)",0 },
	{ "/void@/QXObject/onFocusAboutToChange(/bool,/int)",0 },
	{ "/void@/QXObject/onEnter(/int,/int)",0 },
	{ "/void@/QXObject/onLeave()",0 },
	{ "/void@/QXObject/onPaint(/int,/int,/int,/int,/long)",0 },
	{ "/void@/QXObject/onMove(/int,/int,/int,/int)",0 },
	{ "/void@/QXObject/onResize(/int,/int,/int,/int)",0 },
	{ "/void@/QXObject/onCreate()",0 },
	{ "/void@/QXObject/onDestroy()",0 },
	{ "/void@/QXObject/onShow()",0 },
	{ "/void@/QXObject/onHide()",0 },
	{ "/bool@/QXObject/onClose()",0 },
	{ "/void@/QXObject/onQuit()",0 },
	{ "/void@/QXObject/onParentChange()",0 },
	{ "/void@/QXObject/onParentAboutToChange()",0 },
	{ "/void@/QXObject/onThreadChange()",0 },
	{ "/void@/QXObject/onWindowActivate()",0 },
	{ "/void@/QXObject/onWindowDeactivate()",0 },
	{ "/void@/QXObject/onShowToParent()",0 },
	{ "/void@/QXObject/onHideToParent()",0 },
	{ "/void@/QXObject/onWheel(/int,/int,/int,/int,/int,/bool)",0 },
	{ 0, 0 },
	{ 0, 0 },
	{ 0, 0 },
	{ 0, 0 },
	{ 0, 0 },
	{ 0, 0 },
	{ 0, 0 },
	{ "/void@/QXObject/onClipboard()",0 },
	{ 0, 0 },
	{ 0, 0 },
	{ 0, 0 },
	{ "/void@/QXObject/onWinEventAct()",0 },
	{ "/void@/QXObject/onDeferredDelete()",0 },
	{ "/bool@/QXObject/onDragEnter(/int,/int,/int,/int)",0 },
	{ "/bool@/QXObject/onDragMove(/int,/int,/int,/int)",0 },
	{ "/bool@/QXObject/onDragLeave(/int,/int,/int,/int)",0 },
	{ "/void@/QXObject/onDrop(/*[])",0 },
	{ "/void@/QXObject/onDragResponse()",0 },
	{ 0, 0 },
	{ 0, 0 },
	{ 0, 0 },
	{ 0, 0 },
	{ 0, 0 },
	{ 0, 0 },
	{ "/void@/QXObject/onLayoutRequest()",0 },
	{ "/void@/QXObject/onUpdateRequest()",0 },
	{ "/void@/QXObject/onUpdateLater()",0 },
	{ "/void@/QXObject/onEmbeddingControl()",0 },
	{ "/void@/QXObject/onActivateControl()",0 },
	{ "/void@/QXObject/onDeactivateControl()",0 },
	{ "/void@/QXObject/onContextMenu(/int,/int,/int)",0 },
	{ "/void@/QXObject/onInputMethod()",0 },
	{ "/void@/QXObject/onTabletMove()",0 },
	{ "/void@/QXObject/onLocaleChange()",0 },
	{ "/void@/QXObject/onLanguageChange()",0 },
	{ "/void@/QXObject/onLayoutDirectionChange()",0 },
	{ "/void@/QXObject/onStyle()",0 },
	{ "/void@/QXObject/onTabletPress()",0 },
	{ "/void@/QXObject/onTabletRelease()",0 },
	{ "/void@/QXObject/onOkRequest()",0 },
	{ "/void@/QXObject/onHelpRequest(/int,/int)",0 },
	{ "/void@/QXObject/onIconDrag()",0 },
	{ "/void@/QXObject/onFontChange()",0 },
	{ "/void@/QXObject/onEnabledChange()",0 },
	{ "/void@/QXObject/onActivationChange()",0 },
	{ "/void@/QXObject/onStyleChange()",0 },
	{ "/void@/QXObject/onIconTextChange()",0 },
	{ "/void@/QXObject/onModifiedChange()",0 },
	{ "/void@/QXObject/onMouseTrackingChange()",0 },
	{ "/void@/QXObject/onWindowBlocked()",0 },
	{ "/void@/QXObject/onWindowUnblocked()",0 },
	{ "/void@/QXObject/onWindowStateChange(/int,/int)",0 },
	{ "/void@/QXObject/onReadOnlyChange()",0 },
	{ "/void@/QXObject/onToolTip(/int,/int)",0 },
	{ "/void@/QXObject/onWhatsThis(/int,/int)",0 },
	{ "/void@/QXObject/onStatusTip(/String)",0 },
	{ "/void@/QXObject/onActionChanged()",0 },
	{ "/void@/QXObject/onActionAdded()",0 },
	{ "/void@/QXObject/onActionRemoved()",0 },
	{ "/void@/QXObject/onFileOpen()",0 },
	{ "/void@/QXObject/onShortcut(/int,/int,/bool)",0 },
	{ "/void@/QXObject/onShortcutOverride()",0 },
	{ "/void@/QXObject/onWhatsThisClicked()",0 },
	{ "/void@/QXObject/onToolBarChange()",0 },
	{ "/void@/QXObject/onApplicationActivate()",0 },
	{ "/void@/QXObject/onApplicationDeactivate()",0 },
	{ "/void@/QXObject/onQueryWhatsThis()",0 },
	{ "/void@/QXObject/onEnterWhatsThisMode()",0 },
	{ "/void@/QXObject/onLeaveWhatsThisMode()",0 },
	{ "/void@/QXObject/onZOrderChange()",0 },
	{ "/void@/QXObject/onHoverEnter(/int,/int)",0 },
	{ "/void@/QXObject/onHoverLeave(/int,/int)",0 },
	{ "/void@/QXObject/onHoverMove(/int,/int)",0 },
	{ 0,0 },
	{ 0,0 },
	{ "/void@/QXObject/onAcceptDropsChange()",0 },
	{ "/void@/QXObject/onZeroTimerEvent()",0 },
	{ "/void@/QXObject/onGraphicsSceneMouseMove()",0 },
	{ "/void@/QXObject/onGraphicsSceneMousePress()",0 },
	{ "/void@/QXObject/onGraphicsSceneMouseRelease()",0 },
	{ "/void@/QXObject/onGraphicsSceneMouseDoubleClick()",0 },
	{ "/void@/QXObject/onGraphicsSceneContextMenu()",0 },
	{ "/void@/QXObject/onGraphicsSceneHoverEnter()",0 },
	{ "/void@/QXObject/onGraphicsSceneHoverMove()",0 },
	{ "/void@/QXObject/onGraphicsSceneHoverLeave()",0 },
	{ "/void@/QXObject/onGraphicsSceneHelp()",0 },
	{ "/void@/QXObject/onGraphicsSceneDragEnter()",0 },
	{ "/void@/QXObject/onGraphicsSceneDragMove()",0 },
	{ "/void@/QXObject/onGraphicsSceneDragLeave()",0 },
	{ "/void@/QXObject/onGraphicsSceneDrop()",0 },
	{ "/void@/QXObject/onGraphicsSceneWheel()",0 },
	{ "/void@/QXObject/onKeyboardLayoutChange()",0 },
	{ "/void@/QXObject/onDynamicPropertyChange()",0 },
	{ "/void@/QXObject/onTabletEnterProximity()",0 },
	{ "/void@/QXObject/onTabletLeaveProximity()",0 },
	{ "/void@/QXObject/onNonClientAreaMouseMove()",0 },
	{ "/void@/QXObject/onNonClientAreaMouseButtonPress()",0 },
	{ "/void@/QXObject/onNonClientAreaMouseButtonRelease()",0 },
	{ "/void@/QXObject/onNonClientAreaMouseButtonDblClick()",0 },
	{ "/void@/QXObject/onMacSizeChange()",0 },
	{ "/void@/QXObject/onContentsRectChange()",0 },
	{ "/void@/QXObject/onMacGLWindowChange()",0 },
	{ "/void@/QXObject/onFutureCallOut()",0 },
	{ "/void@/QXObject/onGraphicsSceneResize()",0 },
	{ "/void@/QXObject/onGraphicsSceneMove()",0 },
	{ "/void@/QXObject/onCursorChange()",0 },
	{ "/void@/QXObject/onToolTipChange()",0 },
	{ "/void@/QXObject/onNetworkReplyUpdated()",0 },
	{ "/void@/QXObject/onGrabMouse()",0 },
	{ "/void@/QXObject/onUngrabMouse()",0 },
	{ "/void@/QXObject/onGrabKeyboard()",0 },
	{ "/void@/QXObject/onUngrabKeyboard()",0 },
	{ "/void@/QXObject/onMacGLClearDrawable()",0 },
	{ "/void@/QXObject/onStateMachineSignal()",0 },
	{ "/void@/QXObject/onStateMachineWrapped()",0 },
	{ "/void@/QXObject/onTouchBegin()",0 },
	{ "/void@/QXObject/onTouchUpdate()",0 },
	{ "/void@/QXObject/onTouchEnd()",0 },
	{ "/void@/QXObject/onNativeGesture()",0 },
	{ "/void@/QXObject/onRequestSoftwareInputPanel()",0 },
	{ "/void@/QXObject/onCloseSoftwareInputPanel()",0 },
	{ "/void@/QXObject/onWinIdChange()",0 },
	{ "/void@/QXObject/onGesture()",0 },
	{ "/void@/QXObject/onGestureOverride()",0 },
	{ "/void@/QXObject/onScrollPrepare()",0 },
	{ "/void@/QXObject/onScroll()",0 },
	{ "/void@/QXObject/onExpose()",0 },
	{ "/void@/QXObject/onInputMethodQuery()",0 },
	{ "/void@/QXObject/onOrientationChange()",0 },
	{ "/void@/QXObject/onTouchCancel()",0 },
	{ "/void@/QXObject/onThemeChange()",0 },
	{ "/void@/QXObject/onSockClose()",0 },
	{ "/void@/QXObject/onPlatformPanel()",0 },
	{ "/void@/QXObject/onStyleAnimationUpdate()",0 },
	{ "/void@/QXObject/onApplicationStateChange()",0 },
	{ "/void@/QXObject/onWindowChangeInternal()",0 },
	{ "/void@/QXObject/onScreenChangeInternal()",0 },
	{ "/void@/QXObject/onPlatformSurface()",0 },
	{ "/void@/QXObject/onPointer()",0 },
	{ "/void@/QXObject/onTabletTrackingChange()",0 },
	{ "/void@/QXObject/onTrigger()",0 },
	{ "/void@/QXObject/onItemPressed(/long,/int)",0 },
	{ "/void@/QXObject/onItemClicked(/long,/int)",0 },
	{ "/void@/QXObject/onItemDoubleClicked(/long,/int)",0 },
	{ "/void@/QXObject/onItemActived(/long,/int)",0 },
	{ "/void@/QXObject/onItemEntered(/long,/int)",0 },
	{ "/void@/QXObject/onItemChanged(/long,/int)",0 },
	{ "/void@/QXObject/onItemExpanded(/long)",0 },
	{ "/void@/QXObject/onItemCollapsed(/long)",0 },
	{ "/void@/QXObject/onCurrentItemChanged(/long,/long)",0 },
	{ "/void@/QXObject/onItemSelectionChanged()",0 },
	{ "/void@/QXObject/onNotify(/long)",0 },
	{ "/void@/QXObject/nativeFinalize()",0 },
	{ "/void@/QXObject/onClick(/bool)",0 },
	{ "/void@/QXObject/onToggle(/bool)",0 },
	{ "/void@/QXObject/onPress()",0 },
	{ "/void@/QXObject/onRelease()",0 },
	{ "/void@/QXObject/onFinish(/int)",0 },
	{ "/void@/QXObject/onAccept()",0 },
	{ "/void@/QXObject/onReject()",0 },
	{ "/void@/QXObject/SCEN_CHANGE()" , 0 },
	{ "/void@/QXObject/ON_CALLTIPCLICK(/int)" , 0 },
	{ "/void@/QXObject/ON_CHARADDED(/int)" , 0 },
	{ "/void@/QXObject/ON_DOUBLECLICK(/int,/int,/int)" , 0 },
	{ "/void@/QXObject/ON_DWELLEND(/int,/int,/int)" , 0 },
	{ "/void@/QXObject/ON_DWELLSTART(/int,/int,/int)" , 0 },
	{ "/void@/QXObject/ON_FOCUSIN()" , 0 },
	{ "/void@/QXObject/ON_FOCUSOUT()" , 0 },
	{ "/void@/QXObject/ON_HOTSPOTCLICK(/int,/int)" , 0 },
	{ "/void@/QXObject/ON_HOTSPOTDOUBLECLICK(/int,/int)" , 0 },
	{ "/void@/QXObject/ON_HOTSPOTRELEASECLICK(/int,/int)" , 0 },
	{ "/void@/QXObject/ON_INDICATORCLICK(/int,/int)" , 0 },
	{ "/void@/QXObject/ON_INDICATORRELEASE(/int,/int)" , 0 },
	{ "/void@/QXObject/ON_MACRORECORD(/int,/long,/long)" , 0 },
	{ "/void@/QXObject/ON_MARGINCLICK(/int,/int,/int)" , 0 },
	{ "/void@/QXObject/ON_MARGINRIGHTCLICK(/int,/int,/int)" , 0 },
	{ "/void@/QXObject/ON_MODIFIED(/int,/int,/String,/int,/int,/int,/int,/int,/int,/int)" , 0 },
	{ "/void@/QXObject/ON_MODIFYATTEMPTRO()" , 0 },
	{ "/void@/QXObject/ON_NEEDSHOWN(/int,/int)" , 0 },
	{ "/void@/QXObject/ON_PAINTED()" , 0 },
	{ "/void@/QXObject/ON_SAVEPOINTLEFT()" , 0 },
	{ "/void@/QXObject/ON_SAVEPOINTREACHED()" , 0 },
	{ "/void@/QXObject/ON_STYLENEEDED(/int)" , 0 },
	{ "/void@/QXObject/ON_UPDATEUI(/int)" , 0 },
	{ "/void@/QXObject/ON_USERLISTSELECTION(/String,/int,/int,/int)" , 0 },
	{ "/void@/QXObject/ON_USERLISTSELECTION(/String,/int)" , 0 },
	{ "/void@/QXObject/ON_ZOOM()" , 0 },
	{ "/void@/QXObject/QON_SELCHANGED(/bool)" , 0 },
	{ "/void@/QXObject/ON_AUTOCCANCELLED()" , 0 },
	{ "/void@/QXObject/ON_AUTOCCHARDELETED()" , 0 },
	{ "/void@/QXObject/ON_AUTOCCOMPLETED(/String,/int,/int,/int)" , 0 },
	{ "/void@/QXObject/ON_AUTOCSELECTION(/String,/int,/int,/int)" , 0 },
	{ "/void@/QXObject/ON_AUTOCSELECTION(/String,/int)" , 0 },
	{ "/void@/QXObject/onTextChanged(/String)" , 0 },
	{ "/void@/QXObject/onTextEdited(/String)" , 0 },
	{ "/void@/QXObject/onCursorPositionChanged(/int,/int)" , 0 },
	{ "/void@/QXObject/onReturnPressed()" , 0 },
	{ "/void@/QXObject/onEditingFinished()" , 0 },
	{ "/void@/QXObject/onSelectionChanged()" , 0 },
	{ "/void@/QXObject/onCurrentTextChange(/String)" , 0 },
	{ "/void@/QXObject/onActivated(/int)" , 0 },
	{ "/void@/QXObject/onItemSelected(/int)" , 0 },
	{ "/void@/QXObject/onFileChanged(/String)" , 0 },
	{ "/void@/QXObject/onDirChange(/String)" , 0 },
	{ "/void@/QXObject/onCellChange(/int,/int)" , 0 },
	{ "/void@/QXObject/onItemChange(/long)" , 0 },
	{ "/void@/QXObject/onCellPress(/int,/int)" , 0 },
	{ "/void@/QXObject/onItemPress(/long)" , 0 },
	{ "/void@/QXObject/onCellClick(/int,/int)" , 0 },
	{ "/void@/QXObject/onItemClick(/long)" , 0 },
	{ "/void@/QXObject/onCellDBClick(/int,/int)" , 0 },
	{ "/void@/QXObject/onItemDBClick(/long)" , 0 },
	{ "/void@/QXObject/onCellEnter(/int,/int)" , 0 },
	{ "/void@/QXObject/onItemEnter(/long)" , 0 },
	{ "/void@/QXObject/onCellActived(/int,/int)" , 0 },
	{ "/void@/QXObject/onItemActived(/long)" , 0 },
	{ "/void@/QXObject/onEnumPropertyValueChanged(/long,/int)" , 0 },
	{ "/void@/QXObject/onVariantPropertyValueChanged(/long,/int,/String)" , 0 },
	{ "/void@/QXObject/onVariantPropertyAttributeChanged(/long,/String,/int,/String)" , 0 },
	{ "/void@/QPrintPreviewDialog/onPreviewRequest(/long)" , 0 },
};